# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/BehaviorTrajectory.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg
import std_msgs.msg

class BehaviorTrajectory(genpy.Message):
  _md5sum = "618077a927e8fc3bc8c10db54e2ae18e"
  _type = "autohyu_msgs/BehaviorTrajectory"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header 
uint32 id
uint16 on_ego

autohyu_msgs/TrajectoryBoundary left_boundary
autohyu_msgs/TrajectoryBoundary right_boundary
autohyu_msgs/SpatialTrajectory spatial_trajectory
autohyu_msgs/TemporalTrajectory temporal_trajectory
autohyu_msgs/BehaviorTrajectoryPoint[] point
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: autohyu_msgs/TrajectoryBoundary
autohyu_msgs/TrajectoryBoundaryPoint[] point
================================================================================
MSG: autohyu_msgs/TrajectoryBoundaryPoint
float32 x
float32 y
float32 z
float32 s
float32 n
================================================================================
MSG: autohyu_msgs/SpatialTrajectory
autohyu_msgs/SpatialTrajectoryPoint[] point
================================================================================
MSG: autohyu_msgs/SpatialTrajectoryPoint
float32 x
float32 y
float32 z
bool on_shortest_path
int16 lane_num
================================================================================
MSG: autohyu_msgs/TemporalTrajectory
autohyu_msgs/TemporalTrajectoryPoint[] point
================================================================================
MSG: autohyu_msgs/TemporalTrajectoryPoint
float32 time
float32 distance
float32 curvature
float32 speed
float32 ref_speed
================================================================================
MSG: autohyu_msgs/BehaviorTrajectoryPoint
float64 time
float64 distance
float64 x
float64 y
float64 z
float64 curvature
float64 speed
float64 max_speed
bool    on_shortest_path
int16   lane_num"""
  __slots__ = ['header','id','on_ego','left_boundary','right_boundary','spatial_trajectory','temporal_trajectory','point']
  _slot_types = ['std_msgs/Header','uint32','uint16','autohyu_msgs/TrajectoryBoundary','autohyu_msgs/TrajectoryBoundary','autohyu_msgs/SpatialTrajectory','autohyu_msgs/TemporalTrajectory','autohyu_msgs/BehaviorTrajectoryPoint[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,on_ego,left_boundary,right_boundary,spatial_trajectory,temporal_trajectory,point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BehaviorTrajectory, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.on_ego is None:
        self.on_ego = 0
      if self.left_boundary is None:
        self.left_boundary = autohyu_msgs.msg.TrajectoryBoundary()
      if self.right_boundary is None:
        self.right_boundary = autohyu_msgs.msg.TrajectoryBoundary()
      if self.spatial_trajectory is None:
        self.spatial_trajectory = autohyu_msgs.msg.SpatialTrajectory()
      if self.temporal_trajectory is None:
        self.temporal_trajectory = autohyu_msgs.msg.TemporalTrajectory()
      if self.point is None:
        self.point = []
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.on_ego = 0
      self.left_boundary = autohyu_msgs.msg.TrajectoryBoundary()
      self.right_boundary = autohyu_msgs.msg.TrajectoryBoundary()
      self.spatial_trajectory = autohyu_msgs.msg.SpatialTrajectory()
      self.temporal_trajectory = autohyu_msgs.msg.TemporalTrajectory()
      self.point = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_IH().pack(_x.id, _x.on_ego))
      length = len(self.left_boundary.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_boundary.point:
        _x = val1
        buff.write(_get_struct_5f().pack(_x.x, _x.y, _x.z, _x.s, _x.n))
      length = len(self.right_boundary.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_boundary.point:
        _x = val1
        buff.write(_get_struct_5f().pack(_x.x, _x.y, _x.z, _x.s, _x.n))
      length = len(self.spatial_trajectory.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.spatial_trajectory.point:
        _x = val1
        buff.write(_get_struct_3fBh().pack(_x.x, _x.y, _x.z, _x.on_shortest_path, _x.lane_num))
      length = len(self.temporal_trajectory.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.temporal_trajectory.point:
        _x = val1
        buff.write(_get_struct_5f().pack(_x.time, _x.distance, _x.curvature, _x.speed, _x.ref_speed))
      length = len(self.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.point:
        _x = val1
        buff.write(_get_struct_8dBh().pack(_x.time, _x.distance, _x.x, _x.y, _x.z, _x.curvature, _x.speed, _x.max_speed, _x.on_shortest_path, _x.lane_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_boundary is None:
        self.left_boundary = autohyu_msgs.msg.TrajectoryBoundary()
      if self.right_boundary is None:
        self.right_boundary = autohyu_msgs.msg.TrajectoryBoundary()
      if self.spatial_trajectory is None:
        self.spatial_trajectory = autohyu_msgs.msg.SpatialTrajectory()
      if self.temporal_trajectory is None:
        self.temporal_trajectory = autohyu_msgs.msg.TemporalTrajectory()
      if self.point is None:
        self.point = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.id, _x.on_ego,) = _get_struct_IH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_boundary.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.TrajectoryBoundaryPoint()
        _x = val1
        start = end
        end += 20
        (_x.x, _x.y, _x.z, _x.s, _x.n,) = _get_struct_5f().unpack(str[start:end])
        self.left_boundary.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_boundary.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.TrajectoryBoundaryPoint()
        _x = val1
        start = end
        end += 20
        (_x.x, _x.y, _x.z, _x.s, _x.n,) = _get_struct_5f().unpack(str[start:end])
        self.right_boundary.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.spatial_trajectory.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.SpatialTrajectoryPoint()
        _x = val1
        start = end
        end += 15
        (_x.x, _x.y, _x.z, _x.on_shortest_path, _x.lane_num,) = _get_struct_3fBh().unpack(str[start:end])
        val1.on_shortest_path = bool(val1.on_shortest_path)
        self.spatial_trajectory.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.temporal_trajectory.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.TemporalTrajectoryPoint()
        _x = val1
        start = end
        end += 20
        (_x.time, _x.distance, _x.curvature, _x.speed, _x.ref_speed,) = _get_struct_5f().unpack(str[start:end])
        self.temporal_trajectory.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.BehaviorTrajectoryPoint()
        _x = val1
        start = end
        end += 67
        (_x.time, _x.distance, _x.x, _x.y, _x.z, _x.curvature, _x.speed, _x.max_speed, _x.on_shortest_path, _x.lane_num,) = _get_struct_8dBh().unpack(str[start:end])
        val1.on_shortest_path = bool(val1.on_shortest_path)
        self.point.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_IH().pack(_x.id, _x.on_ego))
      length = len(self.left_boundary.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_boundary.point:
        _x = val1
        buff.write(_get_struct_5f().pack(_x.x, _x.y, _x.z, _x.s, _x.n))
      length = len(self.right_boundary.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_boundary.point:
        _x = val1
        buff.write(_get_struct_5f().pack(_x.x, _x.y, _x.z, _x.s, _x.n))
      length = len(self.spatial_trajectory.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.spatial_trajectory.point:
        _x = val1
        buff.write(_get_struct_3fBh().pack(_x.x, _x.y, _x.z, _x.on_shortest_path, _x.lane_num))
      length = len(self.temporal_trajectory.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.temporal_trajectory.point:
        _x = val1
        buff.write(_get_struct_5f().pack(_x.time, _x.distance, _x.curvature, _x.speed, _x.ref_speed))
      length = len(self.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.point:
        _x = val1
        buff.write(_get_struct_8dBh().pack(_x.time, _x.distance, _x.x, _x.y, _x.z, _x.curvature, _x.speed, _x.max_speed, _x.on_shortest_path, _x.lane_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_boundary is None:
        self.left_boundary = autohyu_msgs.msg.TrajectoryBoundary()
      if self.right_boundary is None:
        self.right_boundary = autohyu_msgs.msg.TrajectoryBoundary()
      if self.spatial_trajectory is None:
        self.spatial_trajectory = autohyu_msgs.msg.SpatialTrajectory()
      if self.temporal_trajectory is None:
        self.temporal_trajectory = autohyu_msgs.msg.TemporalTrajectory()
      if self.point is None:
        self.point = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.id, _x.on_ego,) = _get_struct_IH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_boundary.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.TrajectoryBoundaryPoint()
        _x = val1
        start = end
        end += 20
        (_x.x, _x.y, _x.z, _x.s, _x.n,) = _get_struct_5f().unpack(str[start:end])
        self.left_boundary.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_boundary.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.TrajectoryBoundaryPoint()
        _x = val1
        start = end
        end += 20
        (_x.x, _x.y, _x.z, _x.s, _x.n,) = _get_struct_5f().unpack(str[start:end])
        self.right_boundary.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.spatial_trajectory.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.SpatialTrajectoryPoint()
        _x = val1
        start = end
        end += 15
        (_x.x, _x.y, _x.z, _x.on_shortest_path, _x.lane_num,) = _get_struct_3fBh().unpack(str[start:end])
        val1.on_shortest_path = bool(val1.on_shortest_path)
        self.spatial_trajectory.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.temporal_trajectory.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.TemporalTrajectoryPoint()
        _x = val1
        start = end
        end += 20
        (_x.time, _x.distance, _x.curvature, _x.speed, _x.ref_speed,) = _get_struct_5f().unpack(str[start:end])
        self.temporal_trajectory.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.BehaviorTrajectoryPoint()
        _x = val1
        start = end
        end += 67
        (_x.time, _x.distance, _x.x, _x.y, _x.z, _x.curvature, _x.speed, _x.max_speed, _x.on_shortest_path, _x.lane_num,) = _get_struct_8dBh().unpack(str[start:end])
        val1.on_shortest_path = bool(val1.on_shortest_path)
        self.point.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3fBh = None
def _get_struct_3fBh():
    global _struct_3fBh
    if _struct_3fBh is None:
        _struct_3fBh = struct.Struct("<3fBh")
    return _struct_3fBh
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
_struct_8dBh = None
def _get_struct_8dBh():
    global _struct_8dBh
    if _struct_8dBh is None:
        _struct_8dBh = struct.Struct("<8dBh")
    return _struct_8dBh
_struct_IH = None
def _get_struct_IH():
    global _struct_IH
    if _struct_IH is None:
        _struct_IH = struct.Struct("<IH")
    return _struct_IH
