# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/ControlInputOutput.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg
import std_msgs.msg

class ControlInputOutput(genpy.Message):
  _md5sum = "3ea3f7b2097ca95368fcfd5f0afbc535"
  _type = "autohyu_msgs/ControlInputOutput"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

autohyu_msgs/VehicleState vehicle_state
autohyu_msgs/Trajectory   trajectory
float32[] command_steer
float32[] command_accel_pedal
float32[] command_brake_pedal
float32[] command_speed
float32[] command_acceleration
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: autohyu_msgs/VehicleState
# std_msgs/Header
std_msgs/Header header

# gnss
autohyu_msgs/WGS84 gnss

# position and motion
float64 x
float64 y
float64 z

float64 vx
float64 vy
float64 vz

float64 ax
float64 ay
float64 az

float64 roll
float64 pitch
float64 yaw

float64 roll_vel
float64 pitch_vel
float64 yaw_vel

# vehicle can
autohyu_msgs/VehicleCAN vehicle_can
================================================================================
MSG: autohyu_msgs/WGS84
float64 latitude
float64 longitude
float64 altitude
================================================================================
MSG: autohyu_msgs/VehicleCAN
# std_msgs/Header
std_msgs/Header header

# Measurements
float64 wheel_speed_fl
float64 wheel_speed_fr
float64 wheel_speed_rl
float64 wheel_speed_rr
uint16  vehicle_speed

float64 lateral_accel
float64 longitudinal_accel
float64 yaw_rate

float64 steering_torque
float64 steering_angle
float64 steering_tire_angle
float64 accel_pedal_position
float64 brake_pressure

# AD Status
uint8   cruise_main_status
uint8   cruise_switch_status
uint8   gear_status
uint8   auto_status

# AD Override
uint8   steering_override
uint8   acceleration_override
uint8   brake_override
uint8   sw_estop

# Vehicle Status
uint8   mdps_act_error
uint8   epb_status
uint8   gear_display
uint8   left_turn_signal
uint8   right_turn_signal
uint8   hazard_lamp_status
uint8   kecu_cnt

# Power System
uint8   power_state
uint8   power_MRMdrivingTime
float64 power_main_current
float64 power_sub_current
float64 power_main_voltage
float64 power_sub_voltage

# Mode
uint8   steering_state
uint8   operation_mode
uint8   lateral_ad_mode
uint8   longitudinal_ad_mode

================================================================================
MSG: autohyu_msgs/Trajectory
# std_msgs/Header
std_msgs/Header header

uint16 id
autohyu_msgs/TrajectoryPoint[] point
================================================================================
MSG: autohyu_msgs/TrajectoryPoint
float32 time
float32 distance
uint16  direction
float32 x
float32 y
float32 z
float32 yaw
float32 curvature
float32 speed
float32 acceleration"""
  __slots__ = ['header','vehicle_state','trajectory','command_steer','command_accel_pedal','command_brake_pedal','command_speed','command_acceleration']
  _slot_types = ['std_msgs/Header','autohyu_msgs/VehicleState','autohyu_msgs/Trajectory','float32[]','float32[]','float32[]','float32[]','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,vehicle_state,trajectory,command_steer,command_accel_pedal,command_brake_pedal,command_speed,command_acceleration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControlInputOutput, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.vehicle_state is None:
        self.vehicle_state = autohyu_msgs.msg.VehicleState()
      if self.trajectory is None:
        self.trajectory = autohyu_msgs.msg.Trajectory()
      if self.command_steer is None:
        self.command_steer = []
      if self.command_accel_pedal is None:
        self.command_accel_pedal = []
      if self.command_brake_pedal is None:
        self.command_brake_pedal = []
      if self.command_speed is None:
        self.command_speed = []
      if self.command_acceleration is None:
        self.command_acceleration = []
    else:
      self.header = std_msgs.msg.Header()
      self.vehicle_state = autohyu_msgs.msg.VehicleState()
      self.trajectory = autohyu_msgs.msg.Trajectory()
      self.command_steer = []
      self.command_accel_pedal = []
      self.command_brake_pedal = []
      self.command_speed = []
      self.command_acceleration = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.vehicle_state.header.seq, _x.vehicle_state.header.stamp.secs, _x.vehicle_state.header.stamp.nsecs))
      _x = self.vehicle_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d3I().pack(_x.vehicle_state.gnss.latitude, _x.vehicle_state.gnss.longitude, _x.vehicle_state.gnss.altitude, _x.vehicle_state.x, _x.vehicle_state.y, _x.vehicle_state.z, _x.vehicle_state.vx, _x.vehicle_state.vy, _x.vehicle_state.vz, _x.vehicle_state.ax, _x.vehicle_state.ay, _x.vehicle_state.az, _x.vehicle_state.roll, _x.vehicle_state.pitch, _x.vehicle_state.yaw, _x.vehicle_state.roll_vel, _x.vehicle_state.pitch_vel, _x.vehicle_state.yaw_vel, _x.vehicle_state.vehicle_can.header.seq, _x.vehicle_state.vehicle_can.header.stamp.secs, _x.vehicle_state.vehicle_can.header.stamp.nsecs))
      _x = self.vehicle_state.vehicle_can.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4dH8d17B4d4B3I().pack(_x.vehicle_state.vehicle_can.wheel_speed_fl, _x.vehicle_state.vehicle_can.wheel_speed_fr, _x.vehicle_state.vehicle_can.wheel_speed_rl, _x.vehicle_state.vehicle_can.wheel_speed_rr, _x.vehicle_state.vehicle_can.vehicle_speed, _x.vehicle_state.vehicle_can.lateral_accel, _x.vehicle_state.vehicle_can.longitudinal_accel, _x.vehicle_state.vehicle_can.yaw_rate, _x.vehicle_state.vehicle_can.steering_torque, _x.vehicle_state.vehicle_can.steering_angle, _x.vehicle_state.vehicle_can.steering_tire_angle, _x.vehicle_state.vehicle_can.accel_pedal_position, _x.vehicle_state.vehicle_can.brake_pressure, _x.vehicle_state.vehicle_can.cruise_main_status, _x.vehicle_state.vehicle_can.cruise_switch_status, _x.vehicle_state.vehicle_can.gear_status, _x.vehicle_state.vehicle_can.auto_status, _x.vehicle_state.vehicle_can.steering_override, _x.vehicle_state.vehicle_can.acceleration_override, _x.vehicle_state.vehicle_can.brake_override, _x.vehicle_state.vehicle_can.sw_estop, _x.vehicle_state.vehicle_can.mdps_act_error, _x.vehicle_state.vehicle_can.epb_status, _x.vehicle_state.vehicle_can.gear_display, _x.vehicle_state.vehicle_can.left_turn_signal, _x.vehicle_state.vehicle_can.right_turn_signal, _x.vehicle_state.vehicle_can.hazard_lamp_status, _x.vehicle_state.vehicle_can.kecu_cnt, _x.vehicle_state.vehicle_can.power_state, _x.vehicle_state.vehicle_can.power_MRMdrivingTime, _x.vehicle_state.vehicle_can.power_main_current, _x.vehicle_state.vehicle_can.power_sub_current, _x.vehicle_state.vehicle_can.power_main_voltage, _x.vehicle_state.vehicle_can.power_sub_voltage, _x.vehicle_state.vehicle_can.steering_state, _x.vehicle_state.vehicle_can.operation_mode, _x.vehicle_state.vehicle_can.lateral_ad_mode, _x.vehicle_state.vehicle_can.longitudinal_ad_mode, _x.trajectory.header.seq, _x.trajectory.header.stamp.secs, _x.trajectory.header.stamp.nsecs))
      _x = self.trajectory.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.trajectory.id
      buff.write(_get_struct_H().pack(_x))
      length = len(self.trajectory.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.trajectory.point:
        _x = val1
        buff.write(_get_struct_2fH7f().pack(_x.time, _x.distance, _x.direction, _x.x, _x.y, _x.z, _x.yaw, _x.curvature, _x.speed, _x.acceleration))
      length = len(self.command_steer)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.command_steer))
      length = len(self.command_accel_pedal)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.command_accel_pedal))
      length = len(self.command_brake_pedal)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.command_brake_pedal))
      length = len(self.command_speed)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.command_speed))
      length = len(self.command_acceleration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.command_acceleration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.vehicle_state is None:
        self.vehicle_state = autohyu_msgs.msg.VehicleState()
      if self.trajectory is None:
        self.trajectory = autohyu_msgs.msg.Trajectory()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.vehicle_state.header.seq, _x.vehicle_state.header.stamp.secs, _x.vehicle_state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_state.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.vehicle_state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 156
      (_x.vehicle_state.gnss.latitude, _x.vehicle_state.gnss.longitude, _x.vehicle_state.gnss.altitude, _x.vehicle_state.x, _x.vehicle_state.y, _x.vehicle_state.z, _x.vehicle_state.vx, _x.vehicle_state.vy, _x.vehicle_state.vz, _x.vehicle_state.ax, _x.vehicle_state.ay, _x.vehicle_state.az, _x.vehicle_state.roll, _x.vehicle_state.pitch, _x.vehicle_state.yaw, _x.vehicle_state.roll_vel, _x.vehicle_state.pitch_vel, _x.vehicle_state.yaw_vel, _x.vehicle_state.vehicle_can.header.seq, _x.vehicle_state.vehicle_can.header.stamp.secs, _x.vehicle_state.vehicle_can.header.stamp.nsecs,) = _get_struct_18d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_state.vehicle_can.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.vehicle_state.vehicle_can.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 163
      (_x.vehicle_state.vehicle_can.wheel_speed_fl, _x.vehicle_state.vehicle_can.wheel_speed_fr, _x.vehicle_state.vehicle_can.wheel_speed_rl, _x.vehicle_state.vehicle_can.wheel_speed_rr, _x.vehicle_state.vehicle_can.vehicle_speed, _x.vehicle_state.vehicle_can.lateral_accel, _x.vehicle_state.vehicle_can.longitudinal_accel, _x.vehicle_state.vehicle_can.yaw_rate, _x.vehicle_state.vehicle_can.steering_torque, _x.vehicle_state.vehicle_can.steering_angle, _x.vehicle_state.vehicle_can.steering_tire_angle, _x.vehicle_state.vehicle_can.accel_pedal_position, _x.vehicle_state.vehicle_can.brake_pressure, _x.vehicle_state.vehicle_can.cruise_main_status, _x.vehicle_state.vehicle_can.cruise_switch_status, _x.vehicle_state.vehicle_can.gear_status, _x.vehicle_state.vehicle_can.auto_status, _x.vehicle_state.vehicle_can.steering_override, _x.vehicle_state.vehicle_can.acceleration_override, _x.vehicle_state.vehicle_can.brake_override, _x.vehicle_state.vehicle_can.sw_estop, _x.vehicle_state.vehicle_can.mdps_act_error, _x.vehicle_state.vehicle_can.epb_status, _x.vehicle_state.vehicle_can.gear_display, _x.vehicle_state.vehicle_can.left_turn_signal, _x.vehicle_state.vehicle_can.right_turn_signal, _x.vehicle_state.vehicle_can.hazard_lamp_status, _x.vehicle_state.vehicle_can.kecu_cnt, _x.vehicle_state.vehicle_can.power_state, _x.vehicle_state.vehicle_can.power_MRMdrivingTime, _x.vehicle_state.vehicle_can.power_main_current, _x.vehicle_state.vehicle_can.power_sub_current, _x.vehicle_state.vehicle_can.power_main_voltage, _x.vehicle_state.vehicle_can.power_sub_voltage, _x.vehicle_state.vehicle_can.steering_state, _x.vehicle_state.vehicle_can.operation_mode, _x.vehicle_state.vehicle_can.lateral_ad_mode, _x.vehicle_state.vehicle_can.longitudinal_ad_mode, _x.trajectory.header.seq, _x.trajectory.header.stamp.secs, _x.trajectory.header.stamp.nsecs,) = _get_struct_4dH8d17B4d4B3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trajectory.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.trajectory.header.frame_id = str[start:end]
      start = end
      end += 2
      (self.trajectory.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.trajectory.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.TrajectoryPoint()
        _x = val1
        start = end
        end += 38
        (_x.time, _x.distance, _x.direction, _x.x, _x.y, _x.z, _x.yaw, _x.curvature, _x.speed, _x.acceleration,) = _get_struct_2fH7f().unpack(str[start:end])
        self.trajectory.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_steer = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_accel_pedal = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_brake_pedal = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_speed = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_acceleration = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.vehicle_state.header.seq, _x.vehicle_state.header.stamp.secs, _x.vehicle_state.header.stamp.nsecs))
      _x = self.vehicle_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d3I().pack(_x.vehicle_state.gnss.latitude, _x.vehicle_state.gnss.longitude, _x.vehicle_state.gnss.altitude, _x.vehicle_state.x, _x.vehicle_state.y, _x.vehicle_state.z, _x.vehicle_state.vx, _x.vehicle_state.vy, _x.vehicle_state.vz, _x.vehicle_state.ax, _x.vehicle_state.ay, _x.vehicle_state.az, _x.vehicle_state.roll, _x.vehicle_state.pitch, _x.vehicle_state.yaw, _x.vehicle_state.roll_vel, _x.vehicle_state.pitch_vel, _x.vehicle_state.yaw_vel, _x.vehicle_state.vehicle_can.header.seq, _x.vehicle_state.vehicle_can.header.stamp.secs, _x.vehicle_state.vehicle_can.header.stamp.nsecs))
      _x = self.vehicle_state.vehicle_can.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4dH8d17B4d4B3I().pack(_x.vehicle_state.vehicle_can.wheel_speed_fl, _x.vehicle_state.vehicle_can.wheel_speed_fr, _x.vehicle_state.vehicle_can.wheel_speed_rl, _x.vehicle_state.vehicle_can.wheel_speed_rr, _x.vehicle_state.vehicle_can.vehicle_speed, _x.vehicle_state.vehicle_can.lateral_accel, _x.vehicle_state.vehicle_can.longitudinal_accel, _x.vehicle_state.vehicle_can.yaw_rate, _x.vehicle_state.vehicle_can.steering_torque, _x.vehicle_state.vehicle_can.steering_angle, _x.vehicle_state.vehicle_can.steering_tire_angle, _x.vehicle_state.vehicle_can.accel_pedal_position, _x.vehicle_state.vehicle_can.brake_pressure, _x.vehicle_state.vehicle_can.cruise_main_status, _x.vehicle_state.vehicle_can.cruise_switch_status, _x.vehicle_state.vehicle_can.gear_status, _x.vehicle_state.vehicle_can.auto_status, _x.vehicle_state.vehicle_can.steering_override, _x.vehicle_state.vehicle_can.acceleration_override, _x.vehicle_state.vehicle_can.brake_override, _x.vehicle_state.vehicle_can.sw_estop, _x.vehicle_state.vehicle_can.mdps_act_error, _x.vehicle_state.vehicle_can.epb_status, _x.vehicle_state.vehicle_can.gear_display, _x.vehicle_state.vehicle_can.left_turn_signal, _x.vehicle_state.vehicle_can.right_turn_signal, _x.vehicle_state.vehicle_can.hazard_lamp_status, _x.vehicle_state.vehicle_can.kecu_cnt, _x.vehicle_state.vehicle_can.power_state, _x.vehicle_state.vehicle_can.power_MRMdrivingTime, _x.vehicle_state.vehicle_can.power_main_current, _x.vehicle_state.vehicle_can.power_sub_current, _x.vehicle_state.vehicle_can.power_main_voltage, _x.vehicle_state.vehicle_can.power_sub_voltage, _x.vehicle_state.vehicle_can.steering_state, _x.vehicle_state.vehicle_can.operation_mode, _x.vehicle_state.vehicle_can.lateral_ad_mode, _x.vehicle_state.vehicle_can.longitudinal_ad_mode, _x.trajectory.header.seq, _x.trajectory.header.stamp.secs, _x.trajectory.header.stamp.nsecs))
      _x = self.trajectory.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.trajectory.id
      buff.write(_get_struct_H().pack(_x))
      length = len(self.trajectory.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.trajectory.point:
        _x = val1
        buff.write(_get_struct_2fH7f().pack(_x.time, _x.distance, _x.direction, _x.x, _x.y, _x.z, _x.yaw, _x.curvature, _x.speed, _x.acceleration))
      length = len(self.command_steer)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.command_steer.tostring())
      length = len(self.command_accel_pedal)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.command_accel_pedal.tostring())
      length = len(self.command_brake_pedal)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.command_brake_pedal.tostring())
      length = len(self.command_speed)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.command_speed.tostring())
      length = len(self.command_acceleration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.command_acceleration.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.vehicle_state is None:
        self.vehicle_state = autohyu_msgs.msg.VehicleState()
      if self.trajectory is None:
        self.trajectory = autohyu_msgs.msg.Trajectory()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.vehicle_state.header.seq, _x.vehicle_state.header.stamp.secs, _x.vehicle_state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_state.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.vehicle_state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 156
      (_x.vehicle_state.gnss.latitude, _x.vehicle_state.gnss.longitude, _x.vehicle_state.gnss.altitude, _x.vehicle_state.x, _x.vehicle_state.y, _x.vehicle_state.z, _x.vehicle_state.vx, _x.vehicle_state.vy, _x.vehicle_state.vz, _x.vehicle_state.ax, _x.vehicle_state.ay, _x.vehicle_state.az, _x.vehicle_state.roll, _x.vehicle_state.pitch, _x.vehicle_state.yaw, _x.vehicle_state.roll_vel, _x.vehicle_state.pitch_vel, _x.vehicle_state.yaw_vel, _x.vehicle_state.vehicle_can.header.seq, _x.vehicle_state.vehicle_can.header.stamp.secs, _x.vehicle_state.vehicle_can.header.stamp.nsecs,) = _get_struct_18d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_state.vehicle_can.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.vehicle_state.vehicle_can.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 163
      (_x.vehicle_state.vehicle_can.wheel_speed_fl, _x.vehicle_state.vehicle_can.wheel_speed_fr, _x.vehicle_state.vehicle_can.wheel_speed_rl, _x.vehicle_state.vehicle_can.wheel_speed_rr, _x.vehicle_state.vehicle_can.vehicle_speed, _x.vehicle_state.vehicle_can.lateral_accel, _x.vehicle_state.vehicle_can.longitudinal_accel, _x.vehicle_state.vehicle_can.yaw_rate, _x.vehicle_state.vehicle_can.steering_torque, _x.vehicle_state.vehicle_can.steering_angle, _x.vehicle_state.vehicle_can.steering_tire_angle, _x.vehicle_state.vehicle_can.accel_pedal_position, _x.vehicle_state.vehicle_can.brake_pressure, _x.vehicle_state.vehicle_can.cruise_main_status, _x.vehicle_state.vehicle_can.cruise_switch_status, _x.vehicle_state.vehicle_can.gear_status, _x.vehicle_state.vehicle_can.auto_status, _x.vehicle_state.vehicle_can.steering_override, _x.vehicle_state.vehicle_can.acceleration_override, _x.vehicle_state.vehicle_can.brake_override, _x.vehicle_state.vehicle_can.sw_estop, _x.vehicle_state.vehicle_can.mdps_act_error, _x.vehicle_state.vehicle_can.epb_status, _x.vehicle_state.vehicle_can.gear_display, _x.vehicle_state.vehicle_can.left_turn_signal, _x.vehicle_state.vehicle_can.right_turn_signal, _x.vehicle_state.vehicle_can.hazard_lamp_status, _x.vehicle_state.vehicle_can.kecu_cnt, _x.vehicle_state.vehicle_can.power_state, _x.vehicle_state.vehicle_can.power_MRMdrivingTime, _x.vehicle_state.vehicle_can.power_main_current, _x.vehicle_state.vehicle_can.power_sub_current, _x.vehicle_state.vehicle_can.power_main_voltage, _x.vehicle_state.vehicle_can.power_sub_voltage, _x.vehicle_state.vehicle_can.steering_state, _x.vehicle_state.vehicle_can.operation_mode, _x.vehicle_state.vehicle_can.lateral_ad_mode, _x.vehicle_state.vehicle_can.longitudinal_ad_mode, _x.trajectory.header.seq, _x.trajectory.header.stamp.secs, _x.trajectory.header.stamp.nsecs,) = _get_struct_4dH8d17B4d4B3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trajectory.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.trajectory.header.frame_id = str[start:end]
      start = end
      end += 2
      (self.trajectory.id,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.trajectory.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.TrajectoryPoint()
        _x = val1
        start = end
        end += 38
        (_x.time, _x.distance, _x.direction, _x.x, _x.y, _x.z, _x.yaw, _x.curvature, _x.speed, _x.acceleration,) = _get_struct_2fH7f().unpack(str[start:end])
        self.trajectory.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_steer = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_accel_pedal = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_brake_pedal = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_speed = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.command_acceleration = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18d3I = None
def _get_struct_18d3I():
    global _struct_18d3I
    if _struct_18d3I is None:
        _struct_18d3I = struct.Struct("<18d3I")
    return _struct_18d3I
_struct_2fH7f = None
def _get_struct_2fH7f():
    global _struct_2fH7f
    if _struct_2fH7f is None:
        _struct_2fH7f = struct.Struct("<2fH7f")
    return _struct_2fH7f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4dH8d17B4d4B3I = None
def _get_struct_4dH8d17B4d4B3I():
    global _struct_4dH8d17B4d4B3I
    if _struct_4dH8d17B4d4B3I is None:
        _struct_4dH8d17B4d4B3I = struct.Struct("<4dH8d17B4d4B3I")
    return _struct_4dH8d17B4d4B3I
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
