# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/LaneletRoute.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class LaneletRoute(genpy.Message):
  _md5sum = "cd094afb7c96ccd6501ac3bbfa0c72d6"
  _type = "autohyu_msgs/LaneletRoute"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

autohyu_msgs/Lanelet[] lanelet
autohyu_msgs/LaneletLine[] boundary_line
autohyu_msgs/LaneletLane[] center_lane
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: autohyu_msgs/Lanelet
int64 id
bool is_ego
bool is_goal
bool is_shortest_path
int64 left_boundary_line_id
int64 right_boundary_line_id
autohyu_msgs/LaneletRelation[] relation
autohyu_msgs/LaneletTrafficSign[] traffic_sign
autohyu_msgs/LaneletTrafficSign[] turn_signal
autohyu_msgs/LaneletTrafficLight[] traffic_light
================================================================================
MSG: autohyu_msgs/LaneletRelation
# Relation between lanes
uint8 NONE = 0
uint8 SUCCESSOR = 1
uint8 LEFT = 2
uint8 RIGHT = 3
uint8 ADJACENT_LEFT = 4
uint8 ADJACENT_RIGHT = 5
uint8 CONFLICTING = 6
uint8 AREA = 7

int64 id
uint8 type
================================================================================
MSG: autohyu_msgs/LaneletTrafficSign
int64 id
string element_type
geometry_msgs/Point[] point
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: autohyu_msgs/LaneletTrafficLight
int64 sign_id
int64 intersection_id
string light_type
geometry_msgs/Point[] stop_point
================================================================================
MSG: autohyu_msgs/LaneletLine
int64 id
string line_type
string line_color
geometry_msgs/Point[] point
================================================================================
MSG: autohyu_msgs/LaneletLane
int64 id
int64 lane_num
float64 max_speed
geometry_msgs/Point[] point"""
  __slots__ = ['header','lanelet','boundary_line','center_lane']
  _slot_types = ['std_msgs/Header','autohyu_msgs/Lanelet[]','autohyu_msgs/LaneletLine[]','autohyu_msgs/LaneletLane[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lanelet,boundary_line,center_lane

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LaneletRoute, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lanelet is None:
        self.lanelet = []
      if self.boundary_line is None:
        self.boundary_line = []
      if self.center_lane is None:
        self.center_lane = []
    else:
      self.header = std_msgs.msg.Header()
      self.lanelet = []
      self.boundary_line = []
      self.center_lane = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.lanelet)
      buff.write(_struct_I.pack(length))
      for val1 in self.lanelet:
        _x = val1
        buff.write(_get_struct_q3B2q().pack(_x.id, _x.is_ego, _x.is_goal, _x.is_shortest_path, _x.left_boundary_line_id, _x.right_boundary_line_id))
        length = len(val1.relation)
        buff.write(_struct_I.pack(length))
        for val2 in val1.relation:
          _x = val2
          buff.write(_get_struct_qB().pack(_x.id, _x.type))
        length = len(val1.traffic_sign)
        buff.write(_struct_I.pack(length))
        for val2 in val1.traffic_sign:
          _x = val2.id
          buff.write(_get_struct_q().pack(_x))
          _x = val2.element_type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          length = len(val2.point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.point:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        length = len(val1.turn_signal)
        buff.write(_struct_I.pack(length))
        for val2 in val1.turn_signal:
          _x = val2.id
          buff.write(_get_struct_q().pack(_x))
          _x = val2.element_type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          length = len(val2.point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.point:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        length = len(val1.traffic_light)
        buff.write(_struct_I.pack(length))
        for val2 in val1.traffic_light:
          _x = val2
          buff.write(_get_struct_2q().pack(_x.sign_id, _x.intersection_id))
          _x = val2.light_type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          length = len(val2.stop_point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.stop_point:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.boundary_line)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundary_line:
        _x = val1.id
        buff.write(_get_struct_q().pack(_x))
        _x = val1.line_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.line_color
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.center_lane)
      buff.write(_struct_I.pack(length))
      for val1 in self.center_lane:
        _x = val1
        buff.write(_get_struct_2qd().pack(_x.id, _x.lane_num, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lanelet is None:
        self.lanelet = None
      if self.boundary_line is None:
        self.boundary_line = None
      if self.center_lane is None:
        self.center_lane = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.lanelet = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.Lanelet()
        _x = val1
        start = end
        end += 27
        (_x.id, _x.is_ego, _x.is_goal, _x.is_shortest_path, _x.left_boundary_line_id, _x.right_boundary_line_id,) = _get_struct_q3B2q().unpack(str[start:end])
        val1.is_ego = bool(val1.is_ego)
        val1.is_goal = bool(val1.is_goal)
        val1.is_shortest_path = bool(val1.is_shortest_path)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.relation = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.LaneletRelation()
          _x = val2
          start = end
          end += 9
          (_x.id, _x.type,) = _get_struct_qB().unpack(str[start:end])
          val1.relation.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.traffic_sign = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.LaneletTrafficSign()
          start = end
          end += 8
          (val2.id,) = _get_struct_q().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.element_type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.element_type = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.point = []
          for i in range(0, length):
            val3 = geometry_msgs.msg.Point()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.point.append(val3)
          val1.traffic_sign.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.turn_signal = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.LaneletTrafficSign()
          start = end
          end += 8
          (val2.id,) = _get_struct_q().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.element_type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.element_type = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.point = []
          for i in range(0, length):
            val3 = geometry_msgs.msg.Point()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.point.append(val3)
          val1.turn_signal.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.traffic_light = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.LaneletTrafficLight()
          _x = val2
          start = end
          end += 16
          (_x.sign_id, _x.intersection_id,) = _get_struct_2q().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.light_type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.light_type = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.stop_point = []
          for i in range(0, length):
            val3 = geometry_msgs.msg.Point()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.stop_point.append(val3)
          val1.traffic_light.append(val2)
        self.lanelet.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundary_line = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletLine()
        start = end
        end += 8
        (val1.id,) = _get_struct_q().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.line_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.line_type = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.line_color = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.line_color = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.point.append(val2)
        self.boundary_line.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.center_lane = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletLane()
        _x = val1
        start = end
        end += 24
        (_x.id, _x.lane_num, _x.max_speed,) = _get_struct_2qd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.point.append(val2)
        self.center_lane.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.lanelet)
      buff.write(_struct_I.pack(length))
      for val1 in self.lanelet:
        _x = val1
        buff.write(_get_struct_q3B2q().pack(_x.id, _x.is_ego, _x.is_goal, _x.is_shortest_path, _x.left_boundary_line_id, _x.right_boundary_line_id))
        length = len(val1.relation)
        buff.write(_struct_I.pack(length))
        for val2 in val1.relation:
          _x = val2
          buff.write(_get_struct_qB().pack(_x.id, _x.type))
        length = len(val1.traffic_sign)
        buff.write(_struct_I.pack(length))
        for val2 in val1.traffic_sign:
          _x = val2.id
          buff.write(_get_struct_q().pack(_x))
          _x = val2.element_type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          length = len(val2.point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.point:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        length = len(val1.turn_signal)
        buff.write(_struct_I.pack(length))
        for val2 in val1.turn_signal:
          _x = val2.id
          buff.write(_get_struct_q().pack(_x))
          _x = val2.element_type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          length = len(val2.point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.point:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        length = len(val1.traffic_light)
        buff.write(_struct_I.pack(length))
        for val2 in val1.traffic_light:
          _x = val2
          buff.write(_get_struct_2q().pack(_x.sign_id, _x.intersection_id))
          _x = val2.light_type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          length = len(val2.stop_point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.stop_point:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.boundary_line)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundary_line:
        _x = val1.id
        buff.write(_get_struct_q().pack(_x))
        _x = val1.line_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.line_color
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.center_lane)
      buff.write(_struct_I.pack(length))
      for val1 in self.center_lane:
        _x = val1
        buff.write(_get_struct_2qd().pack(_x.id, _x.lane_num, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lanelet is None:
        self.lanelet = None
      if self.boundary_line is None:
        self.boundary_line = None
      if self.center_lane is None:
        self.center_lane = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.lanelet = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.Lanelet()
        _x = val1
        start = end
        end += 27
        (_x.id, _x.is_ego, _x.is_goal, _x.is_shortest_path, _x.left_boundary_line_id, _x.right_boundary_line_id,) = _get_struct_q3B2q().unpack(str[start:end])
        val1.is_ego = bool(val1.is_ego)
        val1.is_goal = bool(val1.is_goal)
        val1.is_shortest_path = bool(val1.is_shortest_path)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.relation = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.LaneletRelation()
          _x = val2
          start = end
          end += 9
          (_x.id, _x.type,) = _get_struct_qB().unpack(str[start:end])
          val1.relation.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.traffic_sign = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.LaneletTrafficSign()
          start = end
          end += 8
          (val2.id,) = _get_struct_q().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.element_type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.element_type = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.point = []
          for i in range(0, length):
            val3 = geometry_msgs.msg.Point()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.point.append(val3)
          val1.traffic_sign.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.turn_signal = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.LaneletTrafficSign()
          start = end
          end += 8
          (val2.id,) = _get_struct_q().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.element_type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.element_type = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.point = []
          for i in range(0, length):
            val3 = geometry_msgs.msg.Point()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.point.append(val3)
          val1.turn_signal.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.traffic_light = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.LaneletTrafficLight()
          _x = val2
          start = end
          end += 16
          (_x.sign_id, _x.intersection_id,) = _get_struct_2q().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.light_type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.light_type = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.stop_point = []
          for i in range(0, length):
            val3 = geometry_msgs.msg.Point()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.stop_point.append(val3)
          val1.traffic_light.append(val2)
        self.lanelet.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundary_line = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletLine()
        start = end
        end += 8
        (val1.id,) = _get_struct_q().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.line_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.line_type = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.line_color = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.line_color = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.point.append(val2)
        self.boundary_line.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.center_lane = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletLane()
        _x = val1
        start = end
        end += 24
        (_x.id, _x.lane_num, _x.max_speed,) = _get_struct_2qd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.point.append(val2)
        self.center_lane.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2q = None
def _get_struct_2q():
    global _struct_2q
    if _struct_2q is None:
        _struct_2q = struct.Struct("<2q")
    return _struct_2q
_struct_2qd = None
def _get_struct_2qd():
    global _struct_2qd
    if _struct_2qd is None:
        _struct_2qd = struct.Struct("<2qd")
    return _struct_2qd
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_q = None
def _get_struct_q():
    global _struct_q
    if _struct_q is None:
        _struct_q = struct.Struct("<q")
    return _struct_q
_struct_q3B2q = None
def _get_struct_q3B2q():
    global _struct_q3B2q
    if _struct_q3B2q is None:
        _struct_q3B2q = struct.Struct("<q3B2q")
    return _struct_q3B2q
_struct_qB = None
def _get_struct_qB():
    global _struct_qB
    if _struct_qB is None:
        _struct_qB = struct.Struct("<qB")
    return _struct_qB
