# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/Lanelet.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg
import geometry_msgs.msg

class Lanelet(genpy.Message):
  _md5sum = "70053e1f1419d63eb5b6723712e051a8"
  _type = "autohyu_msgs/Lanelet"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 id
bool is_ego
bool is_goal
bool is_shortest_path
int64 left_boundary_line_id
int64 right_boundary_line_id
autohyu_msgs/LaneletRelation[] relation
autohyu_msgs/LaneletTrafficSign[] traffic_sign
autohyu_msgs/LaneletTrafficSign[] turn_signal
autohyu_msgs/LaneletTrafficLight[] traffic_light
================================================================================
MSG: autohyu_msgs/LaneletRelation
# Relation between lanes
uint8 NONE = 0
uint8 SUCCESSOR = 1
uint8 LEFT = 2
uint8 RIGHT = 3
uint8 ADJACENT_LEFT = 4
uint8 ADJACENT_RIGHT = 5
uint8 CONFLICTING = 6
uint8 AREA = 7

int64 id
uint8 type
================================================================================
MSG: autohyu_msgs/LaneletTrafficSign
int64 id
string element_type
geometry_msgs/Point[] point
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: autohyu_msgs/LaneletTrafficLight
int64 sign_id
int64 intersection_id
string light_type
geometry_msgs/Point[] stop_point"""
  __slots__ = ['id','is_ego','is_goal','is_shortest_path','left_boundary_line_id','right_boundary_line_id','relation','traffic_sign','turn_signal','traffic_light']
  _slot_types = ['int64','bool','bool','bool','int64','int64','autohyu_msgs/LaneletRelation[]','autohyu_msgs/LaneletTrafficSign[]','autohyu_msgs/LaneletTrafficSign[]','autohyu_msgs/LaneletTrafficLight[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,is_ego,is_goal,is_shortest_path,left_boundary_line_id,right_boundary_line_id,relation,traffic_sign,turn_signal,traffic_light

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Lanelet, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.is_ego is None:
        self.is_ego = False
      if self.is_goal is None:
        self.is_goal = False
      if self.is_shortest_path is None:
        self.is_shortest_path = False
      if self.left_boundary_line_id is None:
        self.left_boundary_line_id = 0
      if self.right_boundary_line_id is None:
        self.right_boundary_line_id = 0
      if self.relation is None:
        self.relation = []
      if self.traffic_sign is None:
        self.traffic_sign = []
      if self.turn_signal is None:
        self.turn_signal = []
      if self.traffic_light is None:
        self.traffic_light = []
    else:
      self.id = 0
      self.is_ego = False
      self.is_goal = False
      self.is_shortest_path = False
      self.left_boundary_line_id = 0
      self.right_boundary_line_id = 0
      self.relation = []
      self.traffic_sign = []
      self.turn_signal = []
      self.traffic_light = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q3B2q().pack(_x.id, _x.is_ego, _x.is_goal, _x.is_shortest_path, _x.left_boundary_line_id, _x.right_boundary_line_id))
      length = len(self.relation)
      buff.write(_struct_I.pack(length))
      for val1 in self.relation:
        _x = val1
        buff.write(_get_struct_qB().pack(_x.id, _x.type))
      length = len(self.traffic_sign)
      buff.write(_struct_I.pack(length))
      for val1 in self.traffic_sign:
        _x = val1.id
        buff.write(_get_struct_q().pack(_x))
        _x = val1.element_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.turn_signal)
      buff.write(_struct_I.pack(length))
      for val1 in self.turn_signal:
        _x = val1.id
        buff.write(_get_struct_q().pack(_x))
        _x = val1.element_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.traffic_light)
      buff.write(_struct_I.pack(length))
      for val1 in self.traffic_light:
        _x = val1
        buff.write(_get_struct_2q().pack(_x.sign_id, _x.intersection_id))
        _x = val1.light_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(val1.stop_point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.stop_point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.relation is None:
        self.relation = None
      if self.traffic_sign is None:
        self.traffic_sign = None
      if self.turn_signal is None:
        self.turn_signal = None
      if self.traffic_light is None:
        self.traffic_light = None
      end = 0
      _x = self
      start = end
      end += 27
      (_x.id, _x.is_ego, _x.is_goal, _x.is_shortest_path, _x.left_boundary_line_id, _x.right_boundary_line_id,) = _get_struct_q3B2q().unpack(str[start:end])
      self.is_ego = bool(self.is_ego)
      self.is_goal = bool(self.is_goal)
      self.is_shortest_path = bool(self.is_shortest_path)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.relation = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletRelation()
        _x = val1
        start = end
        end += 9
        (_x.id, _x.type,) = _get_struct_qB().unpack(str[start:end])
        self.relation.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.traffic_sign = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletTrafficSign()
        start = end
        end += 8
        (val1.id,) = _get_struct_q().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.element_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.element_type = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.point.append(val2)
        self.traffic_sign.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.turn_signal = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletTrafficSign()
        start = end
        end += 8
        (val1.id,) = _get_struct_q().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.element_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.element_type = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.point.append(val2)
        self.turn_signal.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.traffic_light = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletTrafficLight()
        _x = val1
        start = end
        end += 16
        (_x.sign_id, _x.intersection_id,) = _get_struct_2q().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.light_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.light_type = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.stop_point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.stop_point.append(val2)
        self.traffic_light.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q3B2q().pack(_x.id, _x.is_ego, _x.is_goal, _x.is_shortest_path, _x.left_boundary_line_id, _x.right_boundary_line_id))
      length = len(self.relation)
      buff.write(_struct_I.pack(length))
      for val1 in self.relation:
        _x = val1
        buff.write(_get_struct_qB().pack(_x.id, _x.type))
      length = len(self.traffic_sign)
      buff.write(_struct_I.pack(length))
      for val1 in self.traffic_sign:
        _x = val1.id
        buff.write(_get_struct_q().pack(_x))
        _x = val1.element_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.turn_signal)
      buff.write(_struct_I.pack(length))
      for val1 in self.turn_signal:
        _x = val1.id
        buff.write(_get_struct_q().pack(_x))
        _x = val1.element_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.traffic_light)
      buff.write(_struct_I.pack(length))
      for val1 in self.traffic_light:
        _x = val1
        buff.write(_get_struct_2q().pack(_x.sign_id, _x.intersection_id))
        _x = val1.light_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(val1.stop_point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.stop_point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.relation is None:
        self.relation = None
      if self.traffic_sign is None:
        self.traffic_sign = None
      if self.turn_signal is None:
        self.turn_signal = None
      if self.traffic_light is None:
        self.traffic_light = None
      end = 0
      _x = self
      start = end
      end += 27
      (_x.id, _x.is_ego, _x.is_goal, _x.is_shortest_path, _x.left_boundary_line_id, _x.right_boundary_line_id,) = _get_struct_q3B2q().unpack(str[start:end])
      self.is_ego = bool(self.is_ego)
      self.is_goal = bool(self.is_goal)
      self.is_shortest_path = bool(self.is_shortest_path)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.relation = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletRelation()
        _x = val1
        start = end
        end += 9
        (_x.id, _x.type,) = _get_struct_qB().unpack(str[start:end])
        self.relation.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.traffic_sign = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletTrafficSign()
        start = end
        end += 8
        (val1.id,) = _get_struct_q().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.element_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.element_type = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.point.append(val2)
        self.traffic_sign.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.turn_signal = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletTrafficSign()
        start = end
        end += 8
        (val1.id,) = _get_struct_q().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.element_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.element_type = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.point.append(val2)
        self.turn_signal.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.traffic_light = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.LaneletTrafficLight()
        _x = val1
        start = end
        end += 16
        (_x.sign_id, _x.intersection_id,) = _get_struct_2q().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.light_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.light_type = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.stop_point = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.stop_point.append(val2)
        self.traffic_light.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2q = None
def _get_struct_2q():
    global _struct_2q
    if _struct_2q is None:
        _struct_2q = struct.Struct("<2q")
    return _struct_2q
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_q = None
def _get_struct_q():
    global _struct_q
    if _struct_q is None:
        _struct_q = struct.Struct("<q")
    return _struct_q
_struct_q3B2q = None
def _get_struct_q3B2q():
    global _struct_q3B2q
    if _struct_q3B2q is None:
        _struct_q3B2q = struct.Struct("<q3B2q")
    return _struct_q3B2q
_struct_qB = None
def _get_struct_qB():
    global _struct_qB
    if _struct_qB is None:
        _struct_qB = struct.Struct("<qB")
    return _struct_qB
