# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/PlanningSpace.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg
import std_msgs.msg

class PlanningSpace(genpy.Message):
  _md5sum = "687f829ec6579e0ea7ab55d15b5a120c"
  _type = "autohyu_msgs/PlanningSpace"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

# Ego
autohyu_msgs/PlanningSpaceEgo ego

# Objects
autohyu_msgs/PlanningSpaceObject[] objects

# Vector Map
autohyu_msgs/PlanningSpaceVectorMap[] lanes
autohyu_msgs/PlanningSpaceVectorMap[] routes
autohyu_msgs/PlanningSpaceVectorMap[] crosswalks
autohyu_msgs/PlanningSpaceVectorMap[] goal_routes
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: autohyu_msgs/PlanningSpaceEgo
autohyu_msgs/PlanningSpaceState[] state

================================================================================
MSG: autohyu_msgs/PlanningSpaceState
float64 stamp
float64 x
float64 y
float64 heading
float64 vx
float64 vy
float64 ax
float64 ay
float64 tire_angle
================================================================================
MSG: autohyu_msgs/PlanningSpaceObject
uint64  id
float64 length
float64 width
float64 height
uint16  classification

autohyu_msgs/PlanningSpaceState[] state
================================================================================
MSG: autohyu_msgs/PlanningSpaceVectorMap
int64 id
bool is_dividing_lane
int64 traffic_light_id
int32 traffic_light_color
float64 max_speed
autohyu_msgs/PlanningSpacePoint[] point
autohyu_msgs/PlanningSpacePoint[] left_boundary
autohyu_msgs/PlanningSpacePoint[] right_boundary
================================================================================
MSG: autohyu_msgs/PlanningSpacePoint
float64 x
float64 y
float64 heading
string  traffic_light_id
uint16  traffic_light_color"""
  __slots__ = ['header','ego','objects','lanes','routes','crosswalks','goal_routes']
  _slot_types = ['std_msgs/Header','autohyu_msgs/PlanningSpaceEgo','autohyu_msgs/PlanningSpaceObject[]','autohyu_msgs/PlanningSpaceVectorMap[]','autohyu_msgs/PlanningSpaceVectorMap[]','autohyu_msgs/PlanningSpaceVectorMap[]','autohyu_msgs/PlanningSpaceVectorMap[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ego,objects,lanes,routes,crosswalks,goal_routes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanningSpace, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ego is None:
        self.ego = autohyu_msgs.msg.PlanningSpaceEgo()
      if self.objects is None:
        self.objects = []
      if self.lanes is None:
        self.lanes = []
      if self.routes is None:
        self.routes = []
      if self.crosswalks is None:
        self.crosswalks = []
      if self.goal_routes is None:
        self.goal_routes = []
    else:
      self.header = std_msgs.msg.Header()
      self.ego = autohyu_msgs.msg.PlanningSpaceEgo()
      self.objects = []
      self.lanes = []
      self.routes = []
      self.crosswalks = []
      self.goal_routes = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.ego.state)
      buff.write(_struct_I.pack(length))
      for val1 in self.ego.state:
        _x = val1
        buff.write(_get_struct_9d().pack(_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle))
      length = len(self.objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects:
        _x = val1
        buff.write(_get_struct_Q3dH().pack(_x.id, _x.length, _x.width, _x.height, _x.classification))
        length = len(val1.state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.state:
          _x = val2
          buff.write(_get_struct_9d().pack(_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle))
      length = len(self.lanes)
      buff.write(_struct_I.pack(length))
      for val1 in self.lanes:
        _x = val1
        buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.left_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.left_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.right_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.right_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
      length = len(self.routes)
      buff.write(_struct_I.pack(length))
      for val1 in self.routes:
        _x = val1
        buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.left_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.left_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.right_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.right_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
      length = len(self.crosswalks)
      buff.write(_struct_I.pack(length))
      for val1 in self.crosswalks:
        _x = val1
        buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.left_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.left_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.right_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.right_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
      length = len(self.goal_routes)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal_routes:
        _x = val1
        buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.left_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.left_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.right_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.right_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ego is None:
        self.ego = autohyu_msgs.msg.PlanningSpaceEgo()
      if self.objects is None:
        self.objects = None
      if self.lanes is None:
        self.lanes = None
      if self.routes is None:
        self.routes = None
      if self.crosswalks is None:
        self.crosswalks = None
      if self.goal_routes is None:
        self.goal_routes = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ego.state = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceState()
        _x = val1
        start = end
        end += 72
        (_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle,) = _get_struct_9d().unpack(str[start:end])
        self.ego.state.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceObject()
        _x = val1
        start = end
        end += 34
        (_x.id, _x.length, _x.width, _x.height, _x.classification,) = _get_struct_Q3dH().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.state = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpaceState()
          _x = val2
          start = end
          end += 72
          (_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle,) = _get_struct_9d().unpack(str[start:end])
          val1.state.append(val2)
        self.objects.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.lanes = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceVectorMap()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
        val1.is_dividing_lane = bool(val1.is_dividing_lane)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.point.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.left_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.left_boundary.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.right_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.right_boundary.append(val2)
        self.lanes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.routes = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceVectorMap()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
        val1.is_dividing_lane = bool(val1.is_dividing_lane)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.point.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.left_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.left_boundary.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.right_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.right_boundary.append(val2)
        self.routes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.crosswalks = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceVectorMap()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
        val1.is_dividing_lane = bool(val1.is_dividing_lane)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.point.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.left_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.left_boundary.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.right_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.right_boundary.append(val2)
        self.crosswalks.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal_routes = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceVectorMap()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
        val1.is_dividing_lane = bool(val1.is_dividing_lane)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.point.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.left_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.left_boundary.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.right_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.right_boundary.append(val2)
        self.goal_routes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.ego.state)
      buff.write(_struct_I.pack(length))
      for val1 in self.ego.state:
        _x = val1
        buff.write(_get_struct_9d().pack(_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle))
      length = len(self.objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects:
        _x = val1
        buff.write(_get_struct_Q3dH().pack(_x.id, _x.length, _x.width, _x.height, _x.classification))
        length = len(val1.state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.state:
          _x = val2
          buff.write(_get_struct_9d().pack(_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle))
      length = len(self.lanes)
      buff.write(_struct_I.pack(length))
      for val1 in self.lanes:
        _x = val1
        buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.left_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.left_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.right_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.right_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
      length = len(self.routes)
      buff.write(_struct_I.pack(length))
      for val1 in self.routes:
        _x = val1
        buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.left_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.left_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.right_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.right_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
      length = len(self.crosswalks)
      buff.write(_struct_I.pack(length))
      for val1 in self.crosswalks:
        _x = val1
        buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.left_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.left_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.right_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.right_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
      length = len(self.goal_routes)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal_routes:
        _x = val1
        buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
        length = len(val1.point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.left_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.left_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
        length = len(val1.right_boundary)
        buff.write(_struct_I.pack(length))
        for val2 in val1.right_boundary:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
          _x = val2.traffic_light_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.traffic_light_color
          buff.write(_get_struct_H().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ego is None:
        self.ego = autohyu_msgs.msg.PlanningSpaceEgo()
      if self.objects is None:
        self.objects = None
      if self.lanes is None:
        self.lanes = None
      if self.routes is None:
        self.routes = None
      if self.crosswalks is None:
        self.crosswalks = None
      if self.goal_routes is None:
        self.goal_routes = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ego.state = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceState()
        _x = val1
        start = end
        end += 72
        (_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle,) = _get_struct_9d().unpack(str[start:end])
        self.ego.state.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceObject()
        _x = val1
        start = end
        end += 34
        (_x.id, _x.length, _x.width, _x.height, _x.classification,) = _get_struct_Q3dH().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.state = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpaceState()
          _x = val2
          start = end
          end += 72
          (_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle,) = _get_struct_9d().unpack(str[start:end])
          val1.state.append(val2)
        self.objects.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.lanes = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceVectorMap()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
        val1.is_dividing_lane = bool(val1.is_dividing_lane)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.point.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.left_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.left_boundary.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.right_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.right_boundary.append(val2)
        self.lanes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.routes = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceVectorMap()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
        val1.is_dividing_lane = bool(val1.is_dividing_lane)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.point.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.left_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.left_boundary.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.right_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.right_boundary.append(val2)
        self.routes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.crosswalks = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceVectorMap()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
        val1.is_dividing_lane = bool(val1.is_dividing_lane)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.point.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.left_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.left_boundary.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.right_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.right_boundary.append(val2)
        self.crosswalks.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal_routes = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceVectorMap()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
        val1.is_dividing_lane = bool(val1.is_dividing_lane)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.point = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.point.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.left_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.left_boundary.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.right_boundary = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PlanningSpacePoint()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.traffic_light_id = str[start:end]
          start = end
          end += 2
          (val2.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
          val1.right_boundary.append(val2)
        self.goal_routes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
_struct_Q3dH = None
def _get_struct_Q3dH():
    global _struct_Q3dH
    if _struct_Q3dH is None:
        _struct_Q3dH = struct.Struct("<Q3dH")
    return _struct_Q3dH
_struct_qBqid = None
def _get_struct_qBqid():
    global _struct_qBqid
    if _struct_qBqid is None:
        _struct_qBqid = struct.Struct("<qBqid")
    return _struct_qBqid
