# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/PlanningSpaceObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg

class PlanningSpaceObject(genpy.Message):
  _md5sum = "124f79f4bfef2fc993aeba3f2b4a639a"
  _type = "autohyu_msgs/PlanningSpaceObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64  id
float64 length
float64 width
float64 height
uint16  classification

autohyu_msgs/PlanningSpaceState[] state
================================================================================
MSG: autohyu_msgs/PlanningSpaceState
float64 stamp
float64 x
float64 y
float64 heading
float64 vx
float64 vy
float64 ax
float64 ay
float64 tire_angle"""
  __slots__ = ['id','length','width','height','classification','state']
  _slot_types = ['uint64','float64','float64','float64','uint16','autohyu_msgs/PlanningSpaceState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,length,width,height,classification,state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanningSpaceObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.length is None:
        self.length = 0.
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.classification is None:
        self.classification = 0
      if self.state is None:
        self.state = []
    else:
      self.id = 0
      self.length = 0.
      self.width = 0.
      self.height = 0.
      self.classification = 0
      self.state = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Q3dH().pack(_x.id, _x.length, _x.width, _x.height, _x.classification))
      length = len(self.state)
      buff.write(_struct_I.pack(length))
      for val1 in self.state:
        _x = val1
        buff.write(_get_struct_9d().pack(_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.state is None:
        self.state = None
      end = 0
      _x = self
      start = end
      end += 34
      (_x.id, _x.length, _x.width, _x.height, _x.classification,) = _get_struct_Q3dH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.state = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceState()
        _x = val1
        start = end
        end += 72
        (_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle,) = _get_struct_9d().unpack(str[start:end])
        self.state.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Q3dH().pack(_x.id, _x.length, _x.width, _x.height, _x.classification))
      length = len(self.state)
      buff.write(_struct_I.pack(length))
      for val1 in self.state:
        _x = val1
        buff.write(_get_struct_9d().pack(_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.state is None:
        self.state = None
      end = 0
      _x = self
      start = end
      end += 34
      (_x.id, _x.length, _x.width, _x.height, _x.classification,) = _get_struct_Q3dH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.state = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpaceState()
        _x = val1
        start = end
        end += 72
        (_x.stamp, _x.x, _x.y, _x.heading, _x.vx, _x.vy, _x.ax, _x.ay, _x.tire_angle,) = _get_struct_9d().unpack(str[start:end])
        self.state.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
_struct_Q3dH = None
def _get_struct_Q3dH():
    global _struct_Q3dH
    if _struct_Q3dH is None:
        _struct_Q3dH = struct.Struct("<Q3dH")
    return _struct_Q3dH
