# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/PlanningSpaceVectorMap.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg

class PlanningSpaceVectorMap(genpy.Message):
  _md5sum = "cfb901b2beee878505834aab53d39190"
  _type = "autohyu_msgs/PlanningSpaceVectorMap"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 id
bool is_dividing_lane
int64 traffic_light_id
int32 traffic_light_color
float64 max_speed
autohyu_msgs/PlanningSpacePoint[] point
autohyu_msgs/PlanningSpacePoint[] left_boundary
autohyu_msgs/PlanningSpacePoint[] right_boundary
================================================================================
MSG: autohyu_msgs/PlanningSpacePoint
float64 x
float64 y
float64 heading
string  traffic_light_id
uint16  traffic_light_color"""
  __slots__ = ['id','is_dividing_lane','traffic_light_id','traffic_light_color','max_speed','point','left_boundary','right_boundary']
  _slot_types = ['int64','bool','int64','int32','float64','autohyu_msgs/PlanningSpacePoint[]','autohyu_msgs/PlanningSpacePoint[]','autohyu_msgs/PlanningSpacePoint[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,is_dividing_lane,traffic_light_id,traffic_light_color,max_speed,point,left_boundary,right_boundary

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanningSpaceVectorMap, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.is_dividing_lane is None:
        self.is_dividing_lane = False
      if self.traffic_light_id is None:
        self.traffic_light_id = 0
      if self.traffic_light_color is None:
        self.traffic_light_color = 0
      if self.max_speed is None:
        self.max_speed = 0.
      if self.point is None:
        self.point = []
      if self.left_boundary is None:
        self.left_boundary = []
      if self.right_boundary is None:
        self.right_boundary = []
    else:
      self.id = 0
      self.is_dividing_lane = False
      self.traffic_light_id = 0
      self.traffic_light_color = 0
      self.max_speed = 0.
      self.point = []
      self.left_boundary = []
      self.right_boundary = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
      length = len(self.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.point:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
        _x = val1.traffic_light_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.traffic_light_color
        buff.write(_get_struct_H().pack(_x))
      length = len(self.left_boundary)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_boundary:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
        _x = val1.traffic_light_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.traffic_light_color
        buff.write(_get_struct_H().pack(_x))
      length = len(self.right_boundary)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_boundary:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
        _x = val1.traffic_light_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.traffic_light_color
        buff.write(_get_struct_H().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.point is None:
        self.point = None
      if self.left_boundary is None:
        self.left_boundary = None
      if self.right_boundary is None:
        self.right_boundary = None
      end = 0
      _x = self
      start = end
      end += 29
      (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
      self.is_dividing_lane = bool(self.is_dividing_lane)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpacePoint()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.traffic_light_id = str[start:end]
        start = end
        end += 2
        (val1.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
        self.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_boundary = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpacePoint()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.traffic_light_id = str[start:end]
        start = end
        end += 2
        (val1.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
        self.left_boundary.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_boundary = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpacePoint()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.traffic_light_id = str[start:end]
        start = end
        end += 2
        (val1.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
        self.right_boundary.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_qBqid().pack(_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed))
      length = len(self.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.point:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
        _x = val1.traffic_light_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.traffic_light_color
        buff.write(_get_struct_H().pack(_x))
      length = len(self.left_boundary)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_boundary:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
        _x = val1.traffic_light_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.traffic_light_color
        buff.write(_get_struct_H().pack(_x))
      length = len(self.right_boundary)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_boundary:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.heading))
        _x = val1.traffic_light_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.traffic_light_color
        buff.write(_get_struct_H().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.point is None:
        self.point = None
      if self.left_boundary is None:
        self.left_boundary = None
      if self.right_boundary is None:
        self.right_boundary = None
      end = 0
      _x = self
      start = end
      end += 29
      (_x.id, _x.is_dividing_lane, _x.traffic_light_id, _x.traffic_light_color, _x.max_speed,) = _get_struct_qBqid().unpack(str[start:end])
      self.is_dividing_lane = bool(self.is_dividing_lane)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.point = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpacePoint()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.traffic_light_id = str[start:end]
        start = end
        end += 2
        (val1.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
        self.point.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_boundary = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpacePoint()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.traffic_light_id = str[start:end]
        start = end
        end += 2
        (val1.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
        self.left_boundary.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_boundary = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PlanningSpacePoint()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.heading,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.traffic_light_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.traffic_light_id = str[start:end]
        start = end
        end += 2
        (val1.traffic_light_color,) = _get_struct_H().unpack(str[start:end])
        self.right_boundary.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
_struct_qBqid = None
def _get_struct_qBqid():
    global _struct_qBqid
    if _struct_qBqid is None:
        _struct_qBqid = struct.Struct("<qBqid")
    return _struct_qBqid
