# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/PredictObjects.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg
import std_msgs.msg

class PredictObjects(genpy.Message):
  _md5sum = "5a9a27eb389b4ac10be976e9de502ebf"
  _type = "autohyu_msgs/PredictObjects"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# std_msgs/Header
std_msgs/Header header

# object information
autohyu_msgs/PredictObject[] object

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: autohyu_msgs/PredictObject
# Object information
uint32 id
uint8 classification
uint8 dynamic_state

autohyu_msgs/ObjectDimension dimension
autohyu_msgs/PredictObjectMultimodal[] state_multi
autohyu_msgs/Object3DState[] state

================================================================================
MSG: autohyu_msgs/ObjectDimension
float32 length
float32 width
float32 height

================================================================================
MSG: autohyu_msgs/PredictObjectMultimodal
float64 probability
autohyu_msgs/Object3DState[] state

================================================================================
MSG: autohyu_msgs/Object3DState
std_msgs/Header header

float32 x
float32 y
float32 z
float32 vx
float32 vy
float32 vz
float32 ax
float32 ay
float32 az
float32 roll
float32 pitch
float32 yaw
float32 roll_rate
float32 pitch_rate
float32 yaw_rate"""
  __slots__ = ['header','object']
  _slot_types = ['std_msgs/Header','autohyu_msgs/PredictObject[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,object

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PredictObjects, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = []
    else:
      self.header = std_msgs.msg.Header()
      self.object = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.object)
      buff.write(_struct_I.pack(length))
      for val1 in self.object:
        _x = val1
        buff.write(_get_struct_I2B().pack(_x.id, _x.classification, _x.dynamic_state))
        _v1 = val1.dimension
        _x = _v1
        buff.write(_get_struct_3f().pack(_x.length, _x.width, _x.height))
        length = len(val1.state_multi)
        buff.write(_struct_I.pack(length))
        for val2 in val1.state_multi:
          _x = val2.probability
          buff.write(_get_struct_d().pack(_x))
          length = len(val2.state)
          buff.write(_struct_I.pack(length))
          for val3 in val2.state:
            _v2 = val3.header
            _x = _v2.seq
            buff.write(_get_struct_I().pack(_x))
            _v3 = _v2.stamp
            _x = _v3
            buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
            _x = _v2.frame_id
            length = len(_x)
            if python3 or type(_x) == unicode:
              _x = _x.encode('utf-8')
              length = len(_x)
            buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
            _x = val3
            buff.write(_get_struct_15f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
        length = len(val1.state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.state:
          _v4 = val2.header
          _x = _v4.seq
          buff.write(_get_struct_I().pack(_x))
          _v5 = _v4.stamp
          _x = _v5
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v4.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_15f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.object = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PredictObject()
        _x = val1
        start = end
        end += 6
        (_x.id, _x.classification, _x.dynamic_state,) = _get_struct_I2B().unpack(str[start:end])
        _v6 = val1.dimension
        _x = _v6
        start = end
        end += 12
        (_x.length, _x.width, _x.height,) = _get_struct_3f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.state_multi = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PredictObjectMultimodal()
          start = end
          end += 8
          (val2.probability,) = _get_struct_d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.state = []
          for i in range(0, length):
            val3 = autohyu_msgs.msg.Object3DState()
            _v7 = val3.header
            start = end
            end += 4
            (_v7.seq,) = _get_struct_I().unpack(str[start:end])
            _v8 = _v7.stamp
            _x = _v8
            start = end
            end += 8
            (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
            start = end
            end += 4
            (length,) = _struct_I.unpack(str[start:end])
            start = end
            end += length
            if python3:
              _v7.frame_id = str[start:end].decode('utf-8', 'rosmsg')
            else:
              _v7.frame_id = str[start:end]
            _x = val3
            start = end
            end += 60
            (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
            val2.state.append(val3)
          val1.state_multi.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.state = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.Object3DState()
          _v9 = val2.header
          start = end
          end += 4
          (_v9.seq,) = _get_struct_I().unpack(str[start:end])
          _v10 = _v9.stamp
          _x = _v10
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v9.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v9.frame_id = str[start:end]
          _x = val2
          start = end
          end += 60
          (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
          val1.state.append(val2)
        self.object.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.object)
      buff.write(_struct_I.pack(length))
      for val1 in self.object:
        _x = val1
        buff.write(_get_struct_I2B().pack(_x.id, _x.classification, _x.dynamic_state))
        _v11 = val1.dimension
        _x = _v11
        buff.write(_get_struct_3f().pack(_x.length, _x.width, _x.height))
        length = len(val1.state_multi)
        buff.write(_struct_I.pack(length))
        for val2 in val1.state_multi:
          _x = val2.probability
          buff.write(_get_struct_d().pack(_x))
          length = len(val2.state)
          buff.write(_struct_I.pack(length))
          for val3 in val2.state:
            _v12 = val3.header
            _x = _v12.seq
            buff.write(_get_struct_I().pack(_x))
            _v13 = _v12.stamp
            _x = _v13
            buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
            _x = _v12.frame_id
            length = len(_x)
            if python3 or type(_x) == unicode:
              _x = _x.encode('utf-8')
              length = len(_x)
            buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
            _x = val3
            buff.write(_get_struct_15f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
        length = len(val1.state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.state:
          _v14 = val2.header
          _x = _v14.seq
          buff.write(_get_struct_I().pack(_x))
          _v15 = _v14.stamp
          _x = _v15
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v14.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_15f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.object = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PredictObject()
        _x = val1
        start = end
        end += 6
        (_x.id, _x.classification, _x.dynamic_state,) = _get_struct_I2B().unpack(str[start:end])
        _v16 = val1.dimension
        _x = _v16
        start = end
        end += 12
        (_x.length, _x.width, _x.height,) = _get_struct_3f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.state_multi = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.PredictObjectMultimodal()
          start = end
          end += 8
          (val2.probability,) = _get_struct_d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.state = []
          for i in range(0, length):
            val3 = autohyu_msgs.msg.Object3DState()
            _v17 = val3.header
            start = end
            end += 4
            (_v17.seq,) = _get_struct_I().unpack(str[start:end])
            _v18 = _v17.stamp
            _x = _v18
            start = end
            end += 8
            (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
            start = end
            end += 4
            (length,) = _struct_I.unpack(str[start:end])
            start = end
            end += length
            if python3:
              _v17.frame_id = str[start:end].decode('utf-8', 'rosmsg')
            else:
              _v17.frame_id = str[start:end]
            _x = val3
            start = end
            end += 60
            (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
            val2.state.append(val3)
          val1.state_multi.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.state = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.Object3DState()
          _v19 = val2.header
          start = end
          end += 4
          (_v19.seq,) = _get_struct_I().unpack(str[start:end])
          _v20 = _v19.stamp
          _x = _v20
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v19.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v19.frame_id = str[start:end]
          _x = val2
          start = end
          end += 60
          (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
          val1.state.append(val2)
        self.object.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_15f = None
def _get_struct_15f():
    global _struct_15f
    if _struct_15f is None:
        _struct_15f = struct.Struct("<15f")
    return _struct_15f
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_I2B = None
def _get_struct_I2B():
    global _struct_I2B
    if _struct_I2B is None:
        _struct_I2B = struct.Struct("<I2B")
    return _struct_I2B
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
