# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/PredictObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg
import std_msgs.msg

class PredictObject(genpy.Message):
  _md5sum = "d31c4c1b4494f87ffdc5cd468578ad3a"
  _type = "autohyu_msgs/PredictObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Object information
uint32 id
uint8 classification
uint8 dynamic_state

autohyu_msgs/ObjectDimension dimension
autohyu_msgs/PredictObjectMultimodal[] state_multi
autohyu_msgs/Object3DState[] state

================================================================================
MSG: autohyu_msgs/ObjectDimension
float32 length
float32 width
float32 height

================================================================================
MSG: autohyu_msgs/PredictObjectMultimodal
float64 probability
autohyu_msgs/Object3DState[] state

================================================================================
MSG: autohyu_msgs/Object3DState
std_msgs/Header header

float32 x
float32 y
float32 z
float32 vx
float32 vy
float32 vz
float32 ax
float32 ay
float32 az
float32 roll
float32 pitch
float32 yaw
float32 roll_rate
float32 pitch_rate
float32 yaw_rate
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['id','classification','dynamic_state','dimension','state_multi','state']
  _slot_types = ['uint32','uint8','uint8','autohyu_msgs/ObjectDimension','autohyu_msgs/PredictObjectMultimodal[]','autohyu_msgs/Object3DState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,classification,dynamic_state,dimension,state_multi,state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PredictObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.classification is None:
        self.classification = 0
      if self.dynamic_state is None:
        self.dynamic_state = 0
      if self.dimension is None:
        self.dimension = autohyu_msgs.msg.ObjectDimension()
      if self.state_multi is None:
        self.state_multi = []
      if self.state is None:
        self.state = []
    else:
      self.id = 0
      self.classification = 0
      self.dynamic_state = 0
      self.dimension = autohyu_msgs.msg.ObjectDimension()
      self.state_multi = []
      self.state = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I2B3f().pack(_x.id, _x.classification, _x.dynamic_state, _x.dimension.length, _x.dimension.width, _x.dimension.height))
      length = len(self.state_multi)
      buff.write(_struct_I.pack(length))
      for val1 in self.state_multi:
        _x = val1.probability
        buff.write(_get_struct_d().pack(_x))
        length = len(val1.state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.state:
          _v1 = val2.header
          _x = _v1.seq
          buff.write(_get_struct_I().pack(_x))
          _v2 = _v1.stamp
          _x = _v2
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v1.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_15f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
      length = len(self.state)
      buff.write(_struct_I.pack(length))
      for val1 in self.state:
        _v3 = val1.header
        _x = _v3.seq
        buff.write(_get_struct_I().pack(_x))
        _v4 = _v3.stamp
        _x = _v4
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v3.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_15f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.dimension is None:
        self.dimension = autohyu_msgs.msg.ObjectDimension()
      if self.state_multi is None:
        self.state_multi = None
      if self.state is None:
        self.state = None
      end = 0
      _x = self
      start = end
      end += 18
      (_x.id, _x.classification, _x.dynamic_state, _x.dimension.length, _x.dimension.width, _x.dimension.height,) = _get_struct_I2B3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.state_multi = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PredictObjectMultimodal()
        start = end
        end += 8
        (val1.probability,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.state = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.Object3DState()
          _v5 = val2.header
          start = end
          end += 4
          (_v5.seq,) = _get_struct_I().unpack(str[start:end])
          _v6 = _v5.stamp
          _x = _v6
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v5.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v5.frame_id = str[start:end]
          _x = val2
          start = end
          end += 60
          (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
          val1.state.append(val2)
        self.state_multi.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.state = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.Object3DState()
        _v7 = val1.header
        start = end
        end += 4
        (_v7.seq,) = _get_struct_I().unpack(str[start:end])
        _v8 = _v7.stamp
        _x = _v8
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v7.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v7.frame_id = str[start:end]
        _x = val1
        start = end
        end += 60
        (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
        self.state.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I2B3f().pack(_x.id, _x.classification, _x.dynamic_state, _x.dimension.length, _x.dimension.width, _x.dimension.height))
      length = len(self.state_multi)
      buff.write(_struct_I.pack(length))
      for val1 in self.state_multi:
        _x = val1.probability
        buff.write(_get_struct_d().pack(_x))
        length = len(val1.state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.state:
          _v9 = val2.header
          _x = _v9.seq
          buff.write(_get_struct_I().pack(_x))
          _v10 = _v9.stamp
          _x = _v10
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v9.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_15f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
      length = len(self.state)
      buff.write(_struct_I.pack(length))
      for val1 in self.state:
        _v11 = val1.header
        _x = _v11.seq
        buff.write(_get_struct_I().pack(_x))
        _v12 = _v11.stamp
        _x = _v12
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v11.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_15f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.dimension is None:
        self.dimension = autohyu_msgs.msg.ObjectDimension()
      if self.state_multi is None:
        self.state_multi = None
      if self.state is None:
        self.state = None
      end = 0
      _x = self
      start = end
      end += 18
      (_x.id, _x.classification, _x.dynamic_state, _x.dimension.length, _x.dimension.width, _x.dimension.height,) = _get_struct_I2B3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.state_multi = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.PredictObjectMultimodal()
        start = end
        end += 8
        (val1.probability,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.state = []
        for i in range(0, length):
          val2 = autohyu_msgs.msg.Object3DState()
          _v13 = val2.header
          start = end
          end += 4
          (_v13.seq,) = _get_struct_I().unpack(str[start:end])
          _v14 = _v13.stamp
          _x = _v14
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v13.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v13.frame_id = str[start:end]
          _x = val2
          start = end
          end += 60
          (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
          val1.state.append(val2)
        self.state_multi.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.state = []
      for i in range(0, length):
        val1 = autohyu_msgs.msg.Object3DState()
        _v15 = val1.header
        start = end
        end += 4
        (_v15.seq,) = _get_struct_I().unpack(str[start:end])
        _v16 = _v15.stamp
        _x = _v16
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v15.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v15.frame_id = str[start:end]
        _x = val1
        start = end
        end += 60
        (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
        self.state.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_15f = None
def _get_struct_15f():
    global _struct_15f
    if _struct_15f is None:
        _struct_15f = struct.Struct("<15f")
    return _struct_15f
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_I2B3f = None
def _get_struct_I2B3f():
    global _struct_I2B3f
    if _struct_I2B3f is None:
        _struct_I2B3f = struct.Struct("<I2B3f")
    return _struct_I2B3f
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
