# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/TrackObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg
import std_msgs.msg

class TrackObject(genpy.Message):
  _md5sum = "c567d69f4c89cc5d54e7b9f7798bddba"
  _type = "autohyu_msgs/TrackObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Object information
uint32 id
uint8 classification
uint8 dynamic_state

autohyu_msgs/ObjectDimension dimension
autohyu_msgs/Object3DState state
autohyu_msgs/Object3DState state_covariance

================================================================================
MSG: autohyu_msgs/ObjectDimension
float32 length
float32 width
float32 height

================================================================================
MSG: autohyu_msgs/Object3DState
std_msgs/Header header

float32 x
float32 y
float32 z
float32 vx
float32 vy
float32 vz
float32 ax
float32 ay
float32 az
float32 roll
float32 pitch
float32 yaw
float32 roll_rate
float32 pitch_rate
float32 yaw_rate
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['id','classification','dynamic_state','dimension','state','state_covariance']
  _slot_types = ['uint32','uint8','uint8','autohyu_msgs/ObjectDimension','autohyu_msgs/Object3DState','autohyu_msgs/Object3DState']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,classification,dynamic_state,dimension,state,state_covariance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TrackObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.classification is None:
        self.classification = 0
      if self.dynamic_state is None:
        self.dynamic_state = 0
      if self.dimension is None:
        self.dimension = autohyu_msgs.msg.ObjectDimension()
      if self.state is None:
        self.state = autohyu_msgs.msg.Object3DState()
      if self.state_covariance is None:
        self.state_covariance = autohyu_msgs.msg.Object3DState()
    else:
      self.id = 0
      self.classification = 0
      self.dynamic_state = 0
      self.dimension = autohyu_msgs.msg.ObjectDimension()
      self.state = autohyu_msgs.msg.Object3DState()
      self.state_covariance = autohyu_msgs.msg.Object3DState()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I2B3f3I().pack(_x.id, _x.classification, _x.dynamic_state, _x.dimension.length, _x.dimension.width, _x.dimension.height, _x.state.header.seq, _x.state.header.stamp.secs, _x.state.header.stamp.nsecs))
      _x = self.state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15f3I().pack(_x.state.x, _x.state.y, _x.state.z, _x.state.vx, _x.state.vy, _x.state.vz, _x.state.ax, _x.state.ay, _x.state.az, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.roll_rate, _x.state.pitch_rate, _x.state.yaw_rate, _x.state_covariance.header.seq, _x.state_covariance.header.stamp.secs, _x.state_covariance.header.stamp.nsecs))
      _x = self.state_covariance.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15f().pack(_x.state_covariance.x, _x.state_covariance.y, _x.state_covariance.z, _x.state_covariance.vx, _x.state_covariance.vy, _x.state_covariance.vz, _x.state_covariance.ax, _x.state_covariance.ay, _x.state_covariance.az, _x.state_covariance.roll, _x.state_covariance.pitch, _x.state_covariance.yaw, _x.state_covariance.roll_rate, _x.state_covariance.pitch_rate, _x.state_covariance.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.dimension is None:
        self.dimension = autohyu_msgs.msg.ObjectDimension()
      if self.state is None:
        self.state = autohyu_msgs.msg.Object3DState()
      if self.state_covariance is None:
        self.state_covariance = autohyu_msgs.msg.Object3DState()
      end = 0
      _x = self
      start = end
      end += 30
      (_x.id, _x.classification, _x.dynamic_state, _x.dimension.length, _x.dimension.width, _x.dimension.height, _x.state.header.seq, _x.state.header.stamp.secs, _x.state.header.stamp.nsecs,) = _get_struct_I2B3f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.state.x, _x.state.y, _x.state.z, _x.state.vx, _x.state.vy, _x.state.vz, _x.state.ax, _x.state.ay, _x.state.az, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.roll_rate, _x.state.pitch_rate, _x.state.yaw_rate, _x.state_covariance.header.seq, _x.state_covariance.header.stamp.secs, _x.state_covariance.header.stamp.nsecs,) = _get_struct_15f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state_covariance.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state_covariance.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.state_covariance.x, _x.state_covariance.y, _x.state_covariance.z, _x.state_covariance.vx, _x.state_covariance.vy, _x.state_covariance.vz, _x.state_covariance.ax, _x.state_covariance.ay, _x.state_covariance.az, _x.state_covariance.roll, _x.state_covariance.pitch, _x.state_covariance.yaw, _x.state_covariance.roll_rate, _x.state_covariance.pitch_rate, _x.state_covariance.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I2B3f3I().pack(_x.id, _x.classification, _x.dynamic_state, _x.dimension.length, _x.dimension.width, _x.dimension.height, _x.state.header.seq, _x.state.header.stamp.secs, _x.state.header.stamp.nsecs))
      _x = self.state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15f3I().pack(_x.state.x, _x.state.y, _x.state.z, _x.state.vx, _x.state.vy, _x.state.vz, _x.state.ax, _x.state.ay, _x.state.az, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.roll_rate, _x.state.pitch_rate, _x.state.yaw_rate, _x.state_covariance.header.seq, _x.state_covariance.header.stamp.secs, _x.state_covariance.header.stamp.nsecs))
      _x = self.state_covariance.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15f().pack(_x.state_covariance.x, _x.state_covariance.y, _x.state_covariance.z, _x.state_covariance.vx, _x.state_covariance.vy, _x.state_covariance.vz, _x.state_covariance.ax, _x.state_covariance.ay, _x.state_covariance.az, _x.state_covariance.roll, _x.state_covariance.pitch, _x.state_covariance.yaw, _x.state_covariance.roll_rate, _x.state_covariance.pitch_rate, _x.state_covariance.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.dimension is None:
        self.dimension = autohyu_msgs.msg.ObjectDimension()
      if self.state is None:
        self.state = autohyu_msgs.msg.Object3DState()
      if self.state_covariance is None:
        self.state_covariance = autohyu_msgs.msg.Object3DState()
      end = 0
      _x = self
      start = end
      end += 30
      (_x.id, _x.classification, _x.dynamic_state, _x.dimension.length, _x.dimension.width, _x.dimension.height, _x.state.header.seq, _x.state.header.stamp.secs, _x.state.header.stamp.nsecs,) = _get_struct_I2B3f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.state.x, _x.state.y, _x.state.z, _x.state.vx, _x.state.vy, _x.state.vz, _x.state.ax, _x.state.ay, _x.state.az, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.roll_rate, _x.state.pitch_rate, _x.state.yaw_rate, _x.state_covariance.header.seq, _x.state_covariance.header.stamp.secs, _x.state_covariance.header.stamp.nsecs,) = _get_struct_15f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state_covariance.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state_covariance.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.state_covariance.x, _x.state_covariance.y, _x.state_covariance.z, _x.state_covariance.vx, _x.state_covariance.vy, _x.state_covariance.vz, _x.state_covariance.ax, _x.state_covariance.ay, _x.state_covariance.az, _x.state_covariance.roll, _x.state_covariance.pitch, _x.state_covariance.yaw, _x.state_covariance.roll_rate, _x.state_covariance.pitch_rate, _x.state_covariance.yaw_rate,) = _get_struct_15f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_15f = None
def _get_struct_15f():
    global _struct_15f
    if _struct_15f is None:
        _struct_15f = struct.Struct("<15f")
    return _struct_15f
_struct_15f3I = None
def _get_struct_15f3I():
    global _struct_15f3I
    if _struct_15f3I is None:
        _struct_15f3I = struct.Struct("<15f3I")
    return _struct_15f3I
_struct_I2B3f3I = None
def _get_struct_I2B3f3I():
    global _struct_I2B3f3I
    if _struct_I2B3f3I is None:
        _struct_I2B3f3I = struct.Struct("<I2B3f3I")
    return _struct_I2B3f3I
