# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/VehicleCAN.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class VehicleCAN(genpy.Message):
  _md5sum = "ce768e61bd6f2c0239a3b3e0a9963e4d"
  _type = "autohyu_msgs/VehicleCAN"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# std_msgs/Header
std_msgs/Header header

# Measurements
float64 wheel_speed_fl
float64 wheel_speed_fr
float64 wheel_speed_rl
float64 wheel_speed_rr
uint16  vehicle_speed

float64 lateral_accel
float64 longitudinal_accel
float64 yaw_rate

float64 steering_torque
float64 steering_angle
float64 steering_tire_angle
float64 accel_pedal_position
float64 brake_pressure

# AD Status
uint8   cruise_main_status
uint8   cruise_switch_status
uint8   gear_status
uint8   auto_status

# AD Override
uint8   steering_override
uint8   acceleration_override
uint8   brake_override
uint8   sw_estop

# Vehicle Status
uint8   mdps_act_error
uint8   epb_status
uint8   gear_display
uint8   left_turn_signal
uint8   right_turn_signal
uint8   hazard_lamp_status
uint8   kecu_cnt

# Power System
uint8   power_state
uint8   power_MRMdrivingTime
float64 power_main_current
float64 power_sub_current
float64 power_main_voltage
float64 power_sub_voltage

# Mode
uint8   steering_state
uint8   operation_mode
uint8   lateral_ad_mode
uint8   longitudinal_ad_mode

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','wheel_speed_fl','wheel_speed_fr','wheel_speed_rl','wheel_speed_rr','vehicle_speed','lateral_accel','longitudinal_accel','yaw_rate','steering_torque','steering_angle','steering_tire_angle','accel_pedal_position','brake_pressure','cruise_main_status','cruise_switch_status','gear_status','auto_status','steering_override','acceleration_override','brake_override','sw_estop','mdps_act_error','epb_status','gear_display','left_turn_signal','right_turn_signal','hazard_lamp_status','kecu_cnt','power_state','power_MRMdrivingTime','power_main_current','power_sub_current','power_main_voltage','power_sub_voltage','steering_state','operation_mode','lateral_ad_mode','longitudinal_ad_mode']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','uint16','float64','float64','float64','float64','float64','float64','float64','float64','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','float64','float64','float64','float64','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,wheel_speed_fl,wheel_speed_fr,wheel_speed_rl,wheel_speed_rr,vehicle_speed,lateral_accel,longitudinal_accel,yaw_rate,steering_torque,steering_angle,steering_tire_angle,accel_pedal_position,brake_pressure,cruise_main_status,cruise_switch_status,gear_status,auto_status,steering_override,acceleration_override,brake_override,sw_estop,mdps_act_error,epb_status,gear_display,left_turn_signal,right_turn_signal,hazard_lamp_status,kecu_cnt,power_state,power_MRMdrivingTime,power_main_current,power_sub_current,power_main_voltage,power_sub_voltage,steering_state,operation_mode,lateral_ad_mode,longitudinal_ad_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleCAN, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.wheel_speed_fl is None:
        self.wheel_speed_fl = 0.
      if self.wheel_speed_fr is None:
        self.wheel_speed_fr = 0.
      if self.wheel_speed_rl is None:
        self.wheel_speed_rl = 0.
      if self.wheel_speed_rr is None:
        self.wheel_speed_rr = 0.
      if self.vehicle_speed is None:
        self.vehicle_speed = 0
      if self.lateral_accel is None:
        self.lateral_accel = 0.
      if self.longitudinal_accel is None:
        self.longitudinal_accel = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.steering_torque is None:
        self.steering_torque = 0.
      if self.steering_angle is None:
        self.steering_angle = 0.
      if self.steering_tire_angle is None:
        self.steering_tire_angle = 0.
      if self.accel_pedal_position is None:
        self.accel_pedal_position = 0.
      if self.brake_pressure is None:
        self.brake_pressure = 0.
      if self.cruise_main_status is None:
        self.cruise_main_status = 0
      if self.cruise_switch_status is None:
        self.cruise_switch_status = 0
      if self.gear_status is None:
        self.gear_status = 0
      if self.auto_status is None:
        self.auto_status = 0
      if self.steering_override is None:
        self.steering_override = 0
      if self.acceleration_override is None:
        self.acceleration_override = 0
      if self.brake_override is None:
        self.brake_override = 0
      if self.sw_estop is None:
        self.sw_estop = 0
      if self.mdps_act_error is None:
        self.mdps_act_error = 0
      if self.epb_status is None:
        self.epb_status = 0
      if self.gear_display is None:
        self.gear_display = 0
      if self.left_turn_signal is None:
        self.left_turn_signal = 0
      if self.right_turn_signal is None:
        self.right_turn_signal = 0
      if self.hazard_lamp_status is None:
        self.hazard_lamp_status = 0
      if self.kecu_cnt is None:
        self.kecu_cnt = 0
      if self.power_state is None:
        self.power_state = 0
      if self.power_MRMdrivingTime is None:
        self.power_MRMdrivingTime = 0
      if self.power_main_current is None:
        self.power_main_current = 0.
      if self.power_sub_current is None:
        self.power_sub_current = 0.
      if self.power_main_voltage is None:
        self.power_main_voltage = 0.
      if self.power_sub_voltage is None:
        self.power_sub_voltage = 0.
      if self.steering_state is None:
        self.steering_state = 0
      if self.operation_mode is None:
        self.operation_mode = 0
      if self.lateral_ad_mode is None:
        self.lateral_ad_mode = 0
      if self.longitudinal_ad_mode is None:
        self.longitudinal_ad_mode = 0
    else:
      self.header = std_msgs.msg.Header()
      self.wheel_speed_fl = 0.
      self.wheel_speed_fr = 0.
      self.wheel_speed_rl = 0.
      self.wheel_speed_rr = 0.
      self.vehicle_speed = 0
      self.lateral_accel = 0.
      self.longitudinal_accel = 0.
      self.yaw_rate = 0.
      self.steering_torque = 0.
      self.steering_angle = 0.
      self.steering_tire_angle = 0.
      self.accel_pedal_position = 0.
      self.brake_pressure = 0.
      self.cruise_main_status = 0
      self.cruise_switch_status = 0
      self.gear_status = 0
      self.auto_status = 0
      self.steering_override = 0
      self.acceleration_override = 0
      self.brake_override = 0
      self.sw_estop = 0
      self.mdps_act_error = 0
      self.epb_status = 0
      self.gear_display = 0
      self.left_turn_signal = 0
      self.right_turn_signal = 0
      self.hazard_lamp_status = 0
      self.kecu_cnt = 0
      self.power_state = 0
      self.power_MRMdrivingTime = 0
      self.power_main_current = 0.
      self.power_sub_current = 0.
      self.power_main_voltage = 0.
      self.power_sub_voltage = 0.
      self.steering_state = 0
      self.operation_mode = 0
      self.lateral_ad_mode = 0
      self.longitudinal_ad_mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4dH8d17B4d4B().pack(_x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr, _x.vehicle_speed, _x.lateral_accel, _x.longitudinal_accel, _x.yaw_rate, _x.steering_torque, _x.steering_angle, _x.steering_tire_angle, _x.accel_pedal_position, _x.brake_pressure, _x.cruise_main_status, _x.cruise_switch_status, _x.gear_status, _x.auto_status, _x.steering_override, _x.acceleration_override, _x.brake_override, _x.sw_estop, _x.mdps_act_error, _x.epb_status, _x.gear_display, _x.left_turn_signal, _x.right_turn_signal, _x.hazard_lamp_status, _x.kecu_cnt, _x.power_state, _x.power_MRMdrivingTime, _x.power_main_current, _x.power_sub_current, _x.power_main_voltage, _x.power_sub_voltage, _x.steering_state, _x.operation_mode, _x.lateral_ad_mode, _x.longitudinal_ad_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 151
      (_x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr, _x.vehicle_speed, _x.lateral_accel, _x.longitudinal_accel, _x.yaw_rate, _x.steering_torque, _x.steering_angle, _x.steering_tire_angle, _x.accel_pedal_position, _x.brake_pressure, _x.cruise_main_status, _x.cruise_switch_status, _x.gear_status, _x.auto_status, _x.steering_override, _x.acceleration_override, _x.brake_override, _x.sw_estop, _x.mdps_act_error, _x.epb_status, _x.gear_display, _x.left_turn_signal, _x.right_turn_signal, _x.hazard_lamp_status, _x.kecu_cnt, _x.power_state, _x.power_MRMdrivingTime, _x.power_main_current, _x.power_sub_current, _x.power_main_voltage, _x.power_sub_voltage, _x.steering_state, _x.operation_mode, _x.lateral_ad_mode, _x.longitudinal_ad_mode,) = _get_struct_4dH8d17B4d4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4dH8d17B4d4B().pack(_x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr, _x.vehicle_speed, _x.lateral_accel, _x.longitudinal_accel, _x.yaw_rate, _x.steering_torque, _x.steering_angle, _x.steering_tire_angle, _x.accel_pedal_position, _x.brake_pressure, _x.cruise_main_status, _x.cruise_switch_status, _x.gear_status, _x.auto_status, _x.steering_override, _x.acceleration_override, _x.brake_override, _x.sw_estop, _x.mdps_act_error, _x.epb_status, _x.gear_display, _x.left_turn_signal, _x.right_turn_signal, _x.hazard_lamp_status, _x.kecu_cnt, _x.power_state, _x.power_MRMdrivingTime, _x.power_main_current, _x.power_sub_current, _x.power_main_voltage, _x.power_sub_voltage, _x.steering_state, _x.operation_mode, _x.lateral_ad_mode, _x.longitudinal_ad_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 151
      (_x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr, _x.vehicle_speed, _x.lateral_accel, _x.longitudinal_accel, _x.yaw_rate, _x.steering_torque, _x.steering_angle, _x.steering_tire_angle, _x.accel_pedal_position, _x.brake_pressure, _x.cruise_main_status, _x.cruise_switch_status, _x.gear_status, _x.auto_status, _x.steering_override, _x.acceleration_override, _x.brake_override, _x.sw_estop, _x.mdps_act_error, _x.epb_status, _x.gear_display, _x.left_turn_signal, _x.right_turn_signal, _x.hazard_lamp_status, _x.kecu_cnt, _x.power_state, _x.power_MRMdrivingTime, _x.power_main_current, _x.power_sub_current, _x.power_main_voltage, _x.power_sub_voltage, _x.steering_state, _x.operation_mode, _x.lateral_ad_mode, _x.longitudinal_ad_mode,) = _get_struct_4dH8d17B4d4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4dH8d17B4d4B = None
def _get_struct_4dH8d17B4d4B():
    global _struct_4dH8d17B4d4B
    if _struct_4dH8d17B4d4B is None:
        _struct_4dH8d17B4d4B = struct.Struct("<4dH8d17B4d4B")
    return _struct_4dH8d17B4d4B
