# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autohyu_msgs/VehicleState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autohyu_msgs.msg
import std_msgs.msg

class VehicleState(genpy.Message):
  _md5sum = "82ceef6f5a703e2f0d1a7958db0b5bce"
  _type = "autohyu_msgs/VehicleState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# std_msgs/Header
std_msgs/Header header

# gnss
autohyu_msgs/WGS84 gnss

# position and motion
float64 x
float64 y
float64 z

float64 vx
float64 vy
float64 vz

float64 ax
float64 ay
float64 az

float64 roll
float64 pitch
float64 yaw

float64 roll_vel
float64 pitch_vel
float64 yaw_vel

# vehicle can
autohyu_msgs/VehicleCAN vehicle_can
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: autohyu_msgs/WGS84
float64 latitude
float64 longitude
float64 altitude
================================================================================
MSG: autohyu_msgs/VehicleCAN
# std_msgs/Header
std_msgs/Header header

# Measurements
float64 wheel_speed_fl
float64 wheel_speed_fr
float64 wheel_speed_rl
float64 wheel_speed_rr
uint16  vehicle_speed

float64 lateral_accel
float64 longitudinal_accel
float64 yaw_rate

float64 steering_torque
float64 steering_angle
float64 steering_tire_angle
float64 accel_pedal_position
float64 brake_pressure

# AD Status
uint8   cruise_main_status
uint8   cruise_switch_status
uint8   gear_status
uint8   auto_status

# AD Override
uint8   steering_override
uint8   acceleration_override
uint8   brake_override
uint8   sw_estop

# Vehicle Status
uint8   mdps_act_error
uint8   epb_status
uint8   gear_display
uint8   left_turn_signal
uint8   right_turn_signal
uint8   hazard_lamp_status
uint8   kecu_cnt

# Power System
uint8   power_state
uint8   power_MRMdrivingTime
float64 power_main_current
float64 power_sub_current
float64 power_main_voltage
float64 power_sub_voltage

# Mode
uint8   steering_state
uint8   operation_mode
uint8   lateral_ad_mode
uint8   longitudinal_ad_mode
"""
  __slots__ = ['header','gnss','x','y','z','vx','vy','vz','ax','ay','az','roll','pitch','yaw','roll_vel','pitch_vel','yaw_vel','vehicle_can']
  _slot_types = ['std_msgs/Header','autohyu_msgs/WGS84','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','autohyu_msgs/VehicleCAN']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,gnss,x,y,z,vx,vy,vz,ax,ay,az,roll,pitch,yaw,roll_vel,pitch_vel,yaw_vel,vehicle_can

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gnss is None:
        self.gnss = autohyu_msgs.msg.WGS84()
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.vz is None:
        self.vz = 0.
      if self.ax is None:
        self.ax = 0.
      if self.ay is None:
        self.ay = 0.
      if self.az is None:
        self.az = 0.
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.roll_vel is None:
        self.roll_vel = 0.
      if self.pitch_vel is None:
        self.pitch_vel = 0.
      if self.yaw_vel is None:
        self.yaw_vel = 0.
      if self.vehicle_can is None:
        self.vehicle_can = autohyu_msgs.msg.VehicleCAN()
    else:
      self.header = std_msgs.msg.Header()
      self.gnss = autohyu_msgs.msg.WGS84()
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.vx = 0.
      self.vy = 0.
      self.vz = 0.
      self.ax = 0.
      self.ay = 0.
      self.az = 0.
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.roll_vel = 0.
      self.pitch_vel = 0.
      self.yaw_vel = 0.
      self.vehicle_can = autohyu_msgs.msg.VehicleCAN()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d3I().pack(_x.gnss.latitude, _x.gnss.longitude, _x.gnss.altitude, _x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_vel, _x.pitch_vel, _x.yaw_vel, _x.vehicle_can.header.seq, _x.vehicle_can.header.stamp.secs, _x.vehicle_can.header.stamp.nsecs))
      _x = self.vehicle_can.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4dH8d17B4d4B().pack(_x.vehicle_can.wheel_speed_fl, _x.vehicle_can.wheel_speed_fr, _x.vehicle_can.wheel_speed_rl, _x.vehicle_can.wheel_speed_rr, _x.vehicle_can.vehicle_speed, _x.vehicle_can.lateral_accel, _x.vehicle_can.longitudinal_accel, _x.vehicle_can.yaw_rate, _x.vehicle_can.steering_torque, _x.vehicle_can.steering_angle, _x.vehicle_can.steering_tire_angle, _x.vehicle_can.accel_pedal_position, _x.vehicle_can.brake_pressure, _x.vehicle_can.cruise_main_status, _x.vehicle_can.cruise_switch_status, _x.vehicle_can.gear_status, _x.vehicle_can.auto_status, _x.vehicle_can.steering_override, _x.vehicle_can.acceleration_override, _x.vehicle_can.brake_override, _x.vehicle_can.sw_estop, _x.vehicle_can.mdps_act_error, _x.vehicle_can.epb_status, _x.vehicle_can.gear_display, _x.vehicle_can.left_turn_signal, _x.vehicle_can.right_turn_signal, _x.vehicle_can.hazard_lamp_status, _x.vehicle_can.kecu_cnt, _x.vehicle_can.power_state, _x.vehicle_can.power_MRMdrivingTime, _x.vehicle_can.power_main_current, _x.vehicle_can.power_sub_current, _x.vehicle_can.power_main_voltage, _x.vehicle_can.power_sub_voltage, _x.vehicle_can.steering_state, _x.vehicle_can.operation_mode, _x.vehicle_can.lateral_ad_mode, _x.vehicle_can.longitudinal_ad_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gnss is None:
        self.gnss = autohyu_msgs.msg.WGS84()
      if self.vehicle_can is None:
        self.vehicle_can = autohyu_msgs.msg.VehicleCAN()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 156
      (_x.gnss.latitude, _x.gnss.longitude, _x.gnss.altitude, _x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_vel, _x.pitch_vel, _x.yaw_vel, _x.vehicle_can.header.seq, _x.vehicle_can.header.stamp.secs, _x.vehicle_can.header.stamp.nsecs,) = _get_struct_18d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_can.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.vehicle_can.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 151
      (_x.vehicle_can.wheel_speed_fl, _x.vehicle_can.wheel_speed_fr, _x.vehicle_can.wheel_speed_rl, _x.vehicle_can.wheel_speed_rr, _x.vehicle_can.vehicle_speed, _x.vehicle_can.lateral_accel, _x.vehicle_can.longitudinal_accel, _x.vehicle_can.yaw_rate, _x.vehicle_can.steering_torque, _x.vehicle_can.steering_angle, _x.vehicle_can.steering_tire_angle, _x.vehicle_can.accel_pedal_position, _x.vehicle_can.brake_pressure, _x.vehicle_can.cruise_main_status, _x.vehicle_can.cruise_switch_status, _x.vehicle_can.gear_status, _x.vehicle_can.auto_status, _x.vehicle_can.steering_override, _x.vehicle_can.acceleration_override, _x.vehicle_can.brake_override, _x.vehicle_can.sw_estop, _x.vehicle_can.mdps_act_error, _x.vehicle_can.epb_status, _x.vehicle_can.gear_display, _x.vehicle_can.left_turn_signal, _x.vehicle_can.right_turn_signal, _x.vehicle_can.hazard_lamp_status, _x.vehicle_can.kecu_cnt, _x.vehicle_can.power_state, _x.vehicle_can.power_MRMdrivingTime, _x.vehicle_can.power_main_current, _x.vehicle_can.power_sub_current, _x.vehicle_can.power_main_voltage, _x.vehicle_can.power_sub_voltage, _x.vehicle_can.steering_state, _x.vehicle_can.operation_mode, _x.vehicle_can.lateral_ad_mode, _x.vehicle_can.longitudinal_ad_mode,) = _get_struct_4dH8d17B4d4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d3I().pack(_x.gnss.latitude, _x.gnss.longitude, _x.gnss.altitude, _x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_vel, _x.pitch_vel, _x.yaw_vel, _x.vehicle_can.header.seq, _x.vehicle_can.header.stamp.secs, _x.vehicle_can.header.stamp.nsecs))
      _x = self.vehicle_can.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4dH8d17B4d4B().pack(_x.vehicle_can.wheel_speed_fl, _x.vehicle_can.wheel_speed_fr, _x.vehicle_can.wheel_speed_rl, _x.vehicle_can.wheel_speed_rr, _x.vehicle_can.vehicle_speed, _x.vehicle_can.lateral_accel, _x.vehicle_can.longitudinal_accel, _x.vehicle_can.yaw_rate, _x.vehicle_can.steering_torque, _x.vehicle_can.steering_angle, _x.vehicle_can.steering_tire_angle, _x.vehicle_can.accel_pedal_position, _x.vehicle_can.brake_pressure, _x.vehicle_can.cruise_main_status, _x.vehicle_can.cruise_switch_status, _x.vehicle_can.gear_status, _x.vehicle_can.auto_status, _x.vehicle_can.steering_override, _x.vehicle_can.acceleration_override, _x.vehicle_can.brake_override, _x.vehicle_can.sw_estop, _x.vehicle_can.mdps_act_error, _x.vehicle_can.epb_status, _x.vehicle_can.gear_display, _x.vehicle_can.left_turn_signal, _x.vehicle_can.right_turn_signal, _x.vehicle_can.hazard_lamp_status, _x.vehicle_can.kecu_cnt, _x.vehicle_can.power_state, _x.vehicle_can.power_MRMdrivingTime, _x.vehicle_can.power_main_current, _x.vehicle_can.power_sub_current, _x.vehicle_can.power_main_voltage, _x.vehicle_can.power_sub_voltage, _x.vehicle_can.steering_state, _x.vehicle_can.operation_mode, _x.vehicle_can.lateral_ad_mode, _x.vehicle_can.longitudinal_ad_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gnss is None:
        self.gnss = autohyu_msgs.msg.WGS84()
      if self.vehicle_can is None:
        self.vehicle_can = autohyu_msgs.msg.VehicleCAN()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 156
      (_x.gnss.latitude, _x.gnss.longitude, _x.gnss.altitude, _x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.roll, _x.pitch, _x.yaw, _x.roll_vel, _x.pitch_vel, _x.yaw_vel, _x.vehicle_can.header.seq, _x.vehicle_can.header.stamp.secs, _x.vehicle_can.header.stamp.nsecs,) = _get_struct_18d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_can.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.vehicle_can.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 151
      (_x.vehicle_can.wheel_speed_fl, _x.vehicle_can.wheel_speed_fr, _x.vehicle_can.wheel_speed_rl, _x.vehicle_can.wheel_speed_rr, _x.vehicle_can.vehicle_speed, _x.vehicle_can.lateral_accel, _x.vehicle_can.longitudinal_accel, _x.vehicle_can.yaw_rate, _x.vehicle_can.steering_torque, _x.vehicle_can.steering_angle, _x.vehicle_can.steering_tire_angle, _x.vehicle_can.accel_pedal_position, _x.vehicle_can.brake_pressure, _x.vehicle_can.cruise_main_status, _x.vehicle_can.cruise_switch_status, _x.vehicle_can.gear_status, _x.vehicle_can.auto_status, _x.vehicle_can.steering_override, _x.vehicle_can.acceleration_override, _x.vehicle_can.brake_override, _x.vehicle_can.sw_estop, _x.vehicle_can.mdps_act_error, _x.vehicle_can.epb_status, _x.vehicle_can.gear_display, _x.vehicle_can.left_turn_signal, _x.vehicle_can.right_turn_signal, _x.vehicle_can.hazard_lamp_status, _x.vehicle_can.kecu_cnt, _x.vehicle_can.power_state, _x.vehicle_can.power_MRMdrivingTime, _x.vehicle_can.power_main_current, _x.vehicle_can.power_sub_current, _x.vehicle_can.power_main_voltage, _x.vehicle_can.power_sub_voltage, _x.vehicle_can.steering_state, _x.vehicle_can.operation_mode, _x.vehicle_can.lateral_ad_mode, _x.vehicle_can.longitudinal_ad_mode,) = _get_struct_4dH8d17B4d4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18d3I = None
def _get_struct_18d3I():
    global _struct_18d3I
    if _struct_18d3I is None:
        _struct_18d3I = struct.Struct("<18d3I")
    return _struct_18d3I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4dH8d17B4d4B = None
def _get_struct_4dH8d17B4d4B():
    global _struct_4dH8d17B4d4B
    if _struct_4dH8d17B4d4B is None:
        _struct_4dH8d17B4d4B = struct.Struct("<4dH8d17B4d4B")
    return _struct_4dH8d17B4d4B
