(cl:in-package carmaker_msgs-msg)
(cl:export '(LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ELEVATION-VAL
          ELEVATION
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          EGO_ROLL-VAL
          EGO_ROLL
          EGO_PITCH-VAL
          EGO_PITCH
          EGO_YAW-VAL
          EGO_YAW
          ROLL_RATE-VAL
          ROLL_RATE
          PITCH_RATE-VAL
          PITCH_RATE
          YAW_RATE-VAL
          YAW_RATE
          V_X-VAL
          V_X
          V_Y-VAL
          V_Y
          A_X-VAL
          A_X
          A_Y-VAL
          A_Y
))