# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from carmaker_msgs/Object.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import carmaker_msgs.msg

class Object(genpy.Message):
  _md5sum = "111800c1669628270d9a907e3619e0e5"
  _type = "carmaker_msgs/Object"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Object information
uint8 id
uint8 classification
uint8 lane_id

float32 length 
float32 width 
float32 height 

carmaker_msgs/ObjectState state

================================================================================
MSG: carmaker_msgs/ObjectState
float64 latitude                  # GCS Coordinates latitude
float64 longitude                 # GCS Coordinates longitude
float64 elevation                 # GCS Coordinates elevation

float64 x
float64 y
float64 z

float32 roll                      # yaw in vehicle coordinates [rad]
float32 pitch                     # yaw in vehicle coordinates [rad]
float32 yaw                       # yaw in vehicle coordinates [rad]
float32 ego_roll                      # yaw in vehicle coordinates [rad]
float32 ego_pitch                     # yaw in vehicle coordinates [rad]
float32 ego_yaw                       # yaw in vehicle coordinates [rad]

float32 roll_rate                      # yaw in vehicle coordinates [rad]
float32 pitch_rate                     # yaw in vehicle coordinates [rad]
float32 yaw_rate                       # yaw in vehicle coordinates [rad]

float32 v_x                       # velocity in vehicle coordinates [m/s]
float32 v_y                       # velocity in vehicle coordinates [m/s]
float32 a_x                       # acceleration in vehicle coordinates [m/s^2]
float32 a_y                       # acceleration in vehicle coordinates [m/s^2]
"""
  __slots__ = ['id','classification','lane_id','length','width','height','state']
  _slot_types = ['uint8','uint8','uint8','float32','float32','float32','carmaker_msgs/ObjectState']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,classification,lane_id,length,width,height,state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Object, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.classification is None:
        self.classification = 0
      if self.lane_id is None:
        self.lane_id = 0
      if self.length is None:
        self.length = 0.
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.state is None:
        self.state = carmaker_msgs.msg.ObjectState()
    else:
      self.id = 0
      self.classification = 0
      self.lane_id = 0
      self.length = 0.
      self.width = 0.
      self.height = 0.
      self.state = carmaker_msgs.msg.ObjectState()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B3f6d13f().pack(_x.id, _x.classification, _x.lane_id, _x.length, _x.width, _x.height, _x.state.latitude, _x.state.longitude, _x.state.elevation, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.ego_roll, _x.state.ego_pitch, _x.state.ego_yaw, _x.state.roll_rate, _x.state.pitch_rate, _x.state.yaw_rate, _x.state.v_x, _x.state.v_y, _x.state.a_x, _x.state.a_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.state is None:
        self.state = carmaker_msgs.msg.ObjectState()
      end = 0
      _x = self
      start = end
      end += 115
      (_x.id, _x.classification, _x.lane_id, _x.length, _x.width, _x.height, _x.state.latitude, _x.state.longitude, _x.state.elevation, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.ego_roll, _x.state.ego_pitch, _x.state.ego_yaw, _x.state.roll_rate, _x.state.pitch_rate, _x.state.yaw_rate, _x.state.v_x, _x.state.v_y, _x.state.a_x, _x.state.a_y,) = _get_struct_3B3f6d13f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B3f6d13f().pack(_x.id, _x.classification, _x.lane_id, _x.length, _x.width, _x.height, _x.state.latitude, _x.state.longitude, _x.state.elevation, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.ego_roll, _x.state.ego_pitch, _x.state.ego_yaw, _x.state.roll_rate, _x.state.pitch_rate, _x.state.yaw_rate, _x.state.v_x, _x.state.v_y, _x.state.a_x, _x.state.a_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.state is None:
        self.state = carmaker_msgs.msg.ObjectState()
      end = 0
      _x = self
      start = end
      end += 115
      (_x.id, _x.classification, _x.lane_id, _x.length, _x.width, _x.height, _x.state.latitude, _x.state.longitude, _x.state.elevation, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.ego_roll, _x.state.ego_pitch, _x.state.ego_yaw, _x.state.roll_rate, _x.state.pitch_rate, _x.state.yaw_rate, _x.state.v_x, _x.state.v_y, _x.state.a_x, _x.state.a_y,) = _get_struct_3B3f6d13f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B3f6d13f = None
def _get_struct_3B3f6d13f():
    global _struct_3B3f6d13f
    if _struct_3B3f6d13f is None:
        _struct_3B3f6d13f = struct.Struct("<3B3f6d13f")
    return _struct_3B3f6d13f
