# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from carmaker_msgs/ObjectState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ObjectState(genpy.Message):
  _md5sum = "6a12156275044859859afbe394466b70"
  _type = "carmaker_msgs/ObjectState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 latitude                  # GCS Coordinates latitude
float64 longitude                 # GCS Coordinates longitude
float64 elevation                 # GCS Coordinates elevation

float64 x
float64 y
float64 z

float32 roll                      # yaw in vehicle coordinates [rad]
float32 pitch                     # yaw in vehicle coordinates [rad]
float32 yaw                       # yaw in vehicle coordinates [rad]
float32 ego_roll                      # yaw in vehicle coordinates [rad]
float32 ego_pitch                     # yaw in vehicle coordinates [rad]
float32 ego_yaw                       # yaw in vehicle coordinates [rad]

float32 roll_rate                      # yaw in vehicle coordinates [rad]
float32 pitch_rate                     # yaw in vehicle coordinates [rad]
float32 yaw_rate                       # yaw in vehicle coordinates [rad]

float32 v_x                       # velocity in vehicle coordinates [m/s]
float32 v_y                       # velocity in vehicle coordinates [m/s]
float32 a_x                       # acceleration in vehicle coordinates [m/s^2]
float32 a_y                       # acceleration in vehicle coordinates [m/s^2]
"""
  __slots__ = ['latitude','longitude','elevation','x','y','z','roll','pitch','yaw','ego_roll','ego_pitch','ego_yaw','roll_rate','pitch_rate','yaw_rate','v_x','v_y','a_x','a_y']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latitude,longitude,elevation,x,y,z,roll,pitch,yaw,ego_roll,ego_pitch,ego_yaw,roll_rate,pitch_rate,yaw_rate,v_x,v_y,a_x,a_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.elevation is None:
        self.elevation = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.ego_roll is None:
        self.ego_roll = 0.
      if self.ego_pitch is None:
        self.ego_pitch = 0.
      if self.ego_yaw is None:
        self.ego_yaw = 0.
      if self.roll_rate is None:
        self.roll_rate = 0.
      if self.pitch_rate is None:
        self.pitch_rate = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.v_x is None:
        self.v_x = 0.
      if self.v_y is None:
        self.v_y = 0.
      if self.a_x is None:
        self.a_x = 0.
      if self.a_y is None:
        self.a_y = 0.
    else:
      self.latitude = 0.
      self.longitude = 0.
      self.elevation = 0.
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.ego_roll = 0.
      self.ego_pitch = 0.
      self.ego_yaw = 0.
      self.roll_rate = 0.
      self.pitch_rate = 0.
      self.yaw_rate = 0.
      self.v_x = 0.
      self.v_y = 0.
      self.a_x = 0.
      self.a_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d13f().pack(_x.latitude, _x.longitude, _x.elevation, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.ego_roll, _x.ego_pitch, _x.ego_yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate, _x.v_x, _x.v_y, _x.a_x, _x.a_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 100
      (_x.latitude, _x.longitude, _x.elevation, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.ego_roll, _x.ego_pitch, _x.ego_yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate, _x.v_x, _x.v_y, _x.a_x, _x.a_y,) = _get_struct_6d13f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d13f().pack(_x.latitude, _x.longitude, _x.elevation, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.ego_roll, _x.ego_pitch, _x.ego_yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate, _x.v_x, _x.v_y, _x.a_x, _x.a_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 100
      (_x.latitude, _x.longitude, _x.elevation, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.ego_roll, _x.ego_pitch, _x.ego_yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate, _x.v_x, _x.v_y, _x.a_x, _x.a_y,) = _get_struct_6d13f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d13f = None
def _get_struct_6d13f():
    global _struct_6d13f
    if _struct_6d13f is None:
        _struct_6d13f = struct.Struct("<6d13f")
    return _struct_6d13f
