# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from carmaker_msgs/Objects.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import carmaker_msgs.msg
import std_msgs.msg

class Objects(genpy.Message):
  _md5sum = "aa0a3829c7ec278c7f0d3560362836b3"
  _type = "carmaker_msgs/Objects"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# std_msgs/Header
std_msgs/Header header

# object information
uint16 number_of_objects
carmaker_msgs/Object[] object


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: carmaker_msgs/Object
# Object information
uint8 id
uint8 classification
uint8 lane_id

float32 length 
float32 width 
float32 height 

carmaker_msgs/ObjectState state

================================================================================
MSG: carmaker_msgs/ObjectState
float64 latitude                  # GCS Coordinates latitude
float64 longitude                 # GCS Coordinates longitude
float64 elevation                 # GCS Coordinates elevation

float64 x
float64 y
float64 z

float32 roll                      # yaw in vehicle coordinates [rad]
float32 pitch                     # yaw in vehicle coordinates [rad]
float32 yaw                       # yaw in vehicle coordinates [rad]
float32 ego_roll                      # yaw in vehicle coordinates [rad]
float32 ego_pitch                     # yaw in vehicle coordinates [rad]
float32 ego_yaw                       # yaw in vehicle coordinates [rad]

float32 roll_rate                      # yaw in vehicle coordinates [rad]
float32 pitch_rate                     # yaw in vehicle coordinates [rad]
float32 yaw_rate                       # yaw in vehicle coordinates [rad]

float32 v_x                       # velocity in vehicle coordinates [m/s]
float32 v_y                       # velocity in vehicle coordinates [m/s]
float32 a_x                       # acceleration in vehicle coordinates [m/s^2]
float32 a_y                       # acceleration in vehicle coordinates [m/s^2]
"""
  __slots__ = ['header','number_of_objects','object']
  _slot_types = ['std_msgs/Header','uint16','carmaker_msgs/Object[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,number_of_objects,object

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Objects, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.number_of_objects is None:
        self.number_of_objects = 0
      if self.object is None:
        self.object = []
    else:
      self.header = std_msgs.msg.Header()
      self.number_of_objects = 0
      self.object = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.number_of_objects
      buff.write(_get_struct_H().pack(_x))
      length = len(self.object)
      buff.write(_struct_I.pack(length))
      for val1 in self.object:
        _x = val1
        buff.write(_get_struct_3B3f().pack(_x.id, _x.classification, _x.lane_id, _x.length, _x.width, _x.height))
        _v1 = val1.state
        _x = _v1
        buff.write(_get_struct_6d13f().pack(_x.latitude, _x.longitude, _x.elevation, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.ego_roll, _x.ego_pitch, _x.ego_yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate, _x.v_x, _x.v_y, _x.a_x, _x.a_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 2
      (self.number_of_objects,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.object = []
      for i in range(0, length):
        val1 = carmaker_msgs.msg.Object()
        _x = val1
        start = end
        end += 15
        (_x.id, _x.classification, _x.lane_id, _x.length, _x.width, _x.height,) = _get_struct_3B3f().unpack(str[start:end])
        _v2 = val1.state
        _x = _v2
        start = end
        end += 100
        (_x.latitude, _x.longitude, _x.elevation, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.ego_roll, _x.ego_pitch, _x.ego_yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate, _x.v_x, _x.v_y, _x.a_x, _x.a_y,) = _get_struct_6d13f().unpack(str[start:end])
        self.object.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.number_of_objects
      buff.write(_get_struct_H().pack(_x))
      length = len(self.object)
      buff.write(_struct_I.pack(length))
      for val1 in self.object:
        _x = val1
        buff.write(_get_struct_3B3f().pack(_x.id, _x.classification, _x.lane_id, _x.length, _x.width, _x.height))
        _v3 = val1.state
        _x = _v3
        buff.write(_get_struct_6d13f().pack(_x.latitude, _x.longitude, _x.elevation, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.ego_roll, _x.ego_pitch, _x.ego_yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate, _x.v_x, _x.v_y, _x.a_x, _x.a_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 2
      (self.number_of_objects,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.object = []
      for i in range(0, length):
        val1 = carmaker_msgs.msg.Object()
        _x = val1
        start = end
        end += 15
        (_x.id, _x.classification, _x.lane_id, _x.length, _x.width, _x.height,) = _get_struct_3B3f().unpack(str[start:end])
        _v4 = val1.state
        _x = _v4
        start = end
        end += 100
        (_x.latitude, _x.longitude, _x.elevation, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.ego_roll, _x.ego_pitch, _x.ego_yaw, _x.roll_rate, _x.pitch_rate, _x.yaw_rate, _x.v_x, _x.v_y, _x.a_x, _x.a_y,) = _get_struct_6d13f().unpack(str[start:end])
        self.object.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B3f = None
def _get_struct_3B3f():
    global _struct_3B3f
    if _struct_3B3f is None:
        _struct_3B3f = struct.Struct("<3B3f")
    return _struct_3B3f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6d13f = None
def _get_struct_6d13f():
    global _struct_6d13f
    if _struct_6d13f is None:
        _struct_6d13f = struct.Struct("<6d13f")
    return _struct_6d13f
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
