(cl:in-package autohyu_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          GNSS-VAL
          GNSS
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ROLL_VEL-VAL
          ROLL_VEL
          PITCH_VEL-VAL
          PITCH_VEL
          YAW_VEL-VAL
          YAW_VEL
          VEHICLE_CAN-VAL
          VEHICLE_CAN
))