[Vehicle Origin]
; 0 --- Rear Axle
; 1 --- C.G.
vehicle_origin = 0

[Rear To Ego Mesh]
parent_frame_id = ego_frame
child_frame_id = ego_mesh
transform_xyz_m = 1.51 0.0 0.0
rotation_rpy_deg = 0.0 0.0 0.0

[CG To Ego Mesh]
parent_frame_id = ego_frame
child_frame_id = ego_mesh
transform_xyz_m = 0.0 0.0 0.0
rotation_rpy_deg = 0.0 0.0 0.0