[Lateral Control]

; 0--KINEMATIC_BICYCLE_LMPC
; 1--PURE_PURSUIT
lateral_control_method = 0
reference_time_offset = 0.0
use_reference_speed = 1
time_delay_for_compensators = 0.3
use_understeer_gradient = 1
understeer_gradient_lpf = 0.3
understeer_gradient_rate_limit = 20;deg/s
understeer_gradient_kv = 0.00484182
use_vehicle_twisting_compensator = 0;
vehicle_twisting_constant = 0.00055; motor_torque*vehicle_twisting_constant = steer_bias
max_vehicle_twisting_compensation = 0.1867; deg

[Lateral Kinematic Bicycle LMPC]
step_dt = 0.1
step_num = 39
shift_input_step = 0; for time delay
weight_x = 1
weight_y = 10
weight_yaw = 50
weight_steer = 100
weight_x_end = 0
weight_y_end = 0
weight_yaw_end = 0
weight_steer_end = 0
weight_dsteer = 200  ;20 for good path tracking
avg_distance_error_max = 5.0
avg_yaw_error_max = 100.0

[Pure pursuit]
min_look_ahead = 5.0 ;8.0 6.5
look_ahead_gain = 0.3 ;0.1  0.2 *[m/s]
step_dt = 0.05
step_num = 30

; - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[Longitudinal Control]
; 2--PID
; 4--DELAYED_KINEMATIC_LMPC
longitudinal_control_method = 2
reference_time_offset = 0.0
use_user_speed = 1
user_speed = 20.0 ;[km/h]
zero_speed = -1.0
use_speed_compensator = 0
look_ahead_time = 0.4
ref_speed_lpf = 0.1
vel_kp = 1500
vel_ki = 0
vel_kd = 0.0
max_i_error = 1000
use_cte_decceleration = 0
decceleration_min_cte = 1.2
decceleration_min_accel = 4
decceleration_max_cte = 2.0
decceleration_max_accel = 0.5
pedal_map_file_name = pedal_map_morai_ioniq_5_brake_enhenced.csv

[PID]
vel_kp = 2.0; 1.2 2.0 5.0
vel_ki = 0.05 ; 0.01 0.05
vel_kd = 0
max_i_error = 100
ref_speed_lpf = 0.8 ; 1.0
look_ahead_time = 1.0 ; 0.1 0.3
step_dt = 0.05
step_num = 30


[Longitudinal Delayed Kinematic LMPC]
step_dt = 0.03
step_num = 70
shift_input_step = 0
time_constant = 0.2
max_jerk = 10
weight_damping_ratio = 1
weight_v = 5
weight_a = 10
weight_v_end = 0.0
weight_a_end = 0.0
weight_jerk = 10