; - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
;[Evaluation]
[Evaluation]
mode = morai
one_hit_mode = 1
reset_result = 0 # 0: not reset, 1: reset

departure_threshold = 0.1
global_path_update = 1 # 0: not update, 1: update
moving_average_size = 50
epsilon = 0.5

# Savitzky-Golay Filter
sg_m = 8 # SG_window_size = (2 * SG_M + 1)
sg_n = 2 # SG_polynomial_order
sg_d = 6 # SG_estimate_delay = (1.55 - sg_d * dt) sec

# Detrended Steering std
detrended_steering_std_window = 10 # window size