; - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
;[Map Loader]
[MapLoader]
; utm, local_cartesian
default_projector = local_cartesian

; - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
;[Goalpoint planning]
[Goalpoint planning]
; 0: get one goal point from rviz
; 1: get goal points from rviz
; 2: get goal points from msg from simulator
goal_point_mode = 0
use_predefined_goal = 1
goal_point_x = 739.8751220703125
goal_point_y = -319.21441650390625

; - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
;[Global planning]
[Global planning]

[GlobalPlannningAlgorithm]
resample_distance                = 1.0  ; interpolation resample distance [m]
resample_smoothness              = 0.75 ; interpolation smoothness
ego_lanelet_searching_distance   = 2.0  ; use to find nearest lanelet
lanelet_point_searching_distance = 40.0 ; use to find lanelet point
lanelet_dot_condition            = 0.0  ;
lanelet_dist_condition           = 0.9  ;
lanelet_dist_successor_condition = 0.9  ;
default_maxspeed = 80                   ;[km/h] for non-tagged lanelet

; - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
;[Planning space]
[PlanningSpace]
time_queue = 2.1

[ManageVectorMap]
roi_longitudinal = 150.0
roi_lateral = 150.0
goal_routes_distance = 1.0
num_points = 20
num_goal_routes_points = 120

[ManageQueue]
time_horizon = 2.1
time_resolution = 0.1

; - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
;[Behavior planning]
[BehaviorPlanning]
; 0: not force
force_behavior = 0
; 0: use input data
traffic_light  = 0

[RouteCandidateGeneration]
roi_forward_distance = 1000.0      ;[m]
roi_backward_distance = 200.0      ;[m]
roi_min_distance = 40.0         ;[m]
roi_time = 7.0                  ;[sec]
route_smoothness = 0.99
boundary_smoothness = 0.8

; Speed Related Configs
max_speed = 50          ;[km/h]
max_ax    = 1.0         ;[m/s^2]
min_ax    = -2.0        ;[m/s^2]
stop_ax   = -0.5        ;[m/s^2]
max_ay    = 1.0         ;[m/s^2]
curvature_safety_factor = 1.0
curvature_smoothness = 0.00001
speed_smoothness = 0.075

speed_bump_distance = 3.0 ;[m]
speed_bump_speed = 15.0 ;[km/h]

[CandidateOptimalSelection]
turn_signal_on_time  = 0.5 ;[s]
behavior_change_time = 0.6 ;[s]
time_gap_front = 1.0 ;[s]
time_gap_rear  = 2.0 ;[s]
safety_resolution = 0.1 ;[m]
min_front_safety_distance = 3.0 ;[m]
min_rear_safety_distance = -0.1 ;[m]
mandatory_lane_change_roi = 80.0 ;[m]
mandatory_lk_weight = 1.1