;---------- Carmaker -------------
[Carmaker Vehicle driver]
cfg_i_sim_vx_vy_time_window = 5
cfg_i_sim_ax_ay_time_window = 10
cfg_i_sim_yaw_vel_time_window_ = 3

cfg_cnt = 10
cfg_ay_lpf = 0;
cfg_vy_lpf = 0;
cfg_ay_noise = 0.0;
cfg_vy_noise = 0.0; 

[Carmaker Vehicle control]
use_keyboard_input = 0
use_delayed_input = 0
delay_time = 0.27