// Generated by gencpp from file carmaker_msgs/Control_Signal.msg
// DO NOT EDIT!


#ifndef CARMAKER_MSGS_MESSAGE_CONTROL_SIGNAL_H
#define CARMAKER_MSGS_MESSAGE_CONTROL_SIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace carmaker_msgs
{
template <class ContainerAllocator>
struct Control_Signal_
{
  typedef Control_Signal_<ContainerAllocator> Type;

  Control_Signal_()
    : header()
    , steerangle(0.0)
    , brake(0.0)
    , gas(0.0)
    , accel(0.0)
    , gear(0)  {
    }
  Control_Signal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steerangle(0.0)
    , brake(0.0)
    , gas(0.0)
    , accel(0.0)
    , gear(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _steerangle_type;
  _steerangle_type steerangle;

   typedef float _brake_type;
  _brake_type brake;

   typedef float _gas_type;
  _gas_type gas;

   typedef float _accel_type;
  _accel_type accel;

   typedef int32_t _gear_type;
  _gear_type gear;





  typedef boost::shared_ptr< ::carmaker_msgs::Control_Signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carmaker_msgs::Control_Signal_<ContainerAllocator> const> ConstPtr;

}; // struct Control_Signal_

typedef ::carmaker_msgs::Control_Signal_<std::allocator<void> > Control_Signal;

typedef boost::shared_ptr< ::carmaker_msgs::Control_Signal > Control_SignalPtr;
typedef boost::shared_ptr< ::carmaker_msgs::Control_Signal const> Control_SignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carmaker_msgs::Control_Signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carmaker_msgs::Control_Signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carmaker_msgs::Control_Signal_<ContainerAllocator1> & lhs, const ::carmaker_msgs::Control_Signal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.steerangle == rhs.steerangle &&
    lhs.brake == rhs.brake &&
    lhs.gas == rhs.gas &&
    lhs.accel == rhs.accel &&
    lhs.gear == rhs.gear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carmaker_msgs::Control_Signal_<ContainerAllocator1> & lhs, const ::carmaker_msgs::Control_Signal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carmaker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::Control_Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::Control_Signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::Control_Signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::Control_Signal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::Control_Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::Control_Signal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carmaker_msgs::Control_Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a329d447e45ce3c8e9b8ca16f6f7056";
  }

  static const char* value(const ::carmaker_msgs::Control_Signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a329d447e45ce3cULL;
  static const uint64_t static_value2 = 0x8e9b8ca16f6f7056ULL;
};

template<class ContainerAllocator>
struct DataType< ::carmaker_msgs::Control_Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carmaker_msgs/Control_Signal";
  }

  static const char* value(const ::carmaker_msgs::Control_Signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carmaker_msgs::Control_Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 steerangle #rad -270 ~ 270\n"
"float32 brake      #0: no brake, 1: full brake \n"
"float32 gas        #0: no accel pedal, 1: full accel pedal\n"
"float32 accel      #m/s^2 : if ACC mode is on, this value is used\n"
"int32   gear       #1: drive, 0: neutral, -1: rear, -9: parking\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::carmaker_msgs::Control_Signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carmaker_msgs::Control_Signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steerangle);
      stream.next(m.brake);
      stream.next(m.gas);
      stream.next(m.accel);
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_Signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carmaker_msgs::Control_Signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carmaker_msgs::Control_Signal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steerangle: ";
    Printer<float>::stream(s, indent + "  ", v.steerangle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "brake: ";
    Printer<float>::stream(s, indent + "  ", v.brake);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gas: ";
    Printer<float>::stream(s, indent + "  ", v.gas);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accel: ";
    Printer<float>::stream(s, indent + "  ", v.accel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gear: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARMAKER_MSGS_MESSAGE_CONTROL_SIGNAL_H
