// Generated by gencpp from file carmaker_msgs/GNSS.msg
// DO NOT EDIT!


#ifndef CARMAKER_MSGS_MESSAGE_GNSS_H
#define CARMAKER_MSGS_MESSAGE_GNSS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace carmaker_msgs
{
template <class ContainerAllocator>
struct GNSS_
{
  typedef GNSS_<ContainerAllocator> Type;

  GNSS_()
    : header()
    , time()
    , cycleno(0)
    , synthdelay(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , hdop(0.0)
    , vdop(0.0)  {
    }
  GNSS_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time()
    , cycleno(0)
    , synthdelay(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , hdop(0.0)
    , vdop(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _time_type;
  _time_type time;

   typedef int64_t _cycleno_type;
  _cycleno_type cycleno;

   typedef double _synthdelay_type;
  _synthdelay_type synthdelay;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _hdop_type;
  _hdop_type hdop;

   typedef double _vdop_type;
  _vdop_type vdop;





  typedef boost::shared_ptr< ::carmaker_msgs::GNSS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carmaker_msgs::GNSS_<ContainerAllocator> const> ConstPtr;

}; // struct GNSS_

typedef ::carmaker_msgs::GNSS_<std::allocator<void> > GNSS;

typedef boost::shared_ptr< ::carmaker_msgs::GNSS > GNSSPtr;
typedef boost::shared_ptr< ::carmaker_msgs::GNSS const> GNSSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carmaker_msgs::GNSS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carmaker_msgs::GNSS_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carmaker_msgs::GNSS_<ContainerAllocator1> & lhs, const ::carmaker_msgs::GNSS_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time == rhs.time &&
    lhs.cycleno == rhs.cycleno &&
    lhs.synthdelay == rhs.synthdelay &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.hdop == rhs.hdop &&
    lhs.vdop == rhs.vdop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carmaker_msgs::GNSS_<ContainerAllocator1> & lhs, const ::carmaker_msgs::GNSS_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carmaker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::GNSS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::GNSS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::GNSS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::GNSS_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::GNSS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::GNSS_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carmaker_msgs::GNSS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cea17d642a27853c20b2e5d5dc446a07";
  }

  static const char* value(const ::carmaker_msgs::GNSS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcea17d642a27853cULL;
  static const uint64_t static_value2 = 0x20b2e5d5dc446a07ULL;
};

template<class ContainerAllocator>
struct DataType< ::carmaker_msgs::GNSS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carmaker_msgs/GNSS";
  }

  static const char* value(const ::carmaker_msgs::GNSS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carmaker_msgs::GNSS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Message from CarMaker ROS Node to external ROS Node\n"
"#\n"
"\n"
"# General\n"
"Header  header                                 # General ROS Header (optional)\n"
"time    time                                   # ROS time when message was sent (optional)\n"
"int64   cycleno                                # Cycle number since simulation start (optional)\n"
"float64 synthdelay                             # Synthetic delay to check synchronization (optional)\n"
"\n"
"float64 latitude                               # Latitude [degrees]\n"
"float64 longitude                              # Longitude [degrees]\n"
"float64 altitude                               # Altitude [m]\n"
"\n"
"float64 hdop                                   # Precision in horizontal positioning\n"
"float64 vdop                                   # Precision in vertical positioning\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::carmaker_msgs::GNSS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carmaker_msgs::GNSS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.cycleno);
      stream.next(m.synthdelay);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.hdop);
      stream.next(m.vdop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GNSS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carmaker_msgs::GNSS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carmaker_msgs::GNSS_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cycleno: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cycleno);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "synthdelay: ";
    Printer<double>::stream(s, indent + "  ", v.synthdelay);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hdop: ";
    Printer<double>::stream(s, indent + "  ", v.hdop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vdop: ";
    Printer<double>::stream(s, indent + "  ", v.vdop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARMAKER_MSGS_MESSAGE_GNSS_H
