// Generated by gencpp from file carmaker_msgs/InitResponse.msg
// DO NOT EDIT!


#ifndef CARMAKER_MSGS_MESSAGE_INITRESPONSE_H
#define CARMAKER_MSGS_MESSAGE_INITRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carmaker_msgs
{
template <class ContainerAllocator>
struct InitResponse_
{
  typedef InitResponse_<ContainerAllocator> Type;

  InitResponse_()
    : success(false)
    , cycletime(0)
    , message()  {
    }
  InitResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , cycletime(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _cycletime_type;
  _cycletime_type cycletime;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::carmaker_msgs::InitResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carmaker_msgs::InitResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitResponse_

typedef ::carmaker_msgs::InitResponse_<std::allocator<void> > InitResponse;

typedef boost::shared_ptr< ::carmaker_msgs::InitResponse > InitResponsePtr;
typedef boost::shared_ptr< ::carmaker_msgs::InitResponse const> InitResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carmaker_msgs::InitResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carmaker_msgs::InitResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carmaker_msgs::InitResponse_<ContainerAllocator1> & lhs, const ::carmaker_msgs::InitResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.cycletime == rhs.cycletime &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carmaker_msgs::InitResponse_<ContainerAllocator1> & lhs, const ::carmaker_msgs::InitResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carmaker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::InitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::InitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::InitResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::InitResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::InitResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::InitResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carmaker_msgs::InitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b782e011a181d0d03948ac040f0f5458";
  }

  static const char* value(const ::carmaker_msgs::InitResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb782e011a181d0d0ULL;
  static const uint64_t static_value2 = 0x3948ac040f0f5458ULL;
};

template<class ContainerAllocator>
struct DataType< ::carmaker_msgs::InitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carmaker_msgs/InitResponse";
  }

  static const char* value(const ::carmaker_msgs::InitResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carmaker_msgs::InitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool   success    # indicate successful run of triggered service\n"
"int32  cycletime  # default cycle time in ms \n"
"string message    # informational, e.g. for error messages\n"
"\n"
;
  }

  static const char* value(const ::carmaker_msgs::InitResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carmaker_msgs::InitResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.cycletime);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carmaker_msgs::InitResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carmaker_msgs::InitResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cycletime: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cycletime);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARMAKER_MSGS_MESSAGE_INITRESPONSE_H
