// Generated by gencpp from file carmaker_msgs/Init.msg
// DO NOT EDIT!


#ifndef CARMAKER_MSGS_MESSAGE_INIT_H
#define CARMAKER_MSGS_MESSAGE_INIT_H

#include <ros/service_traits.h>


#include <carmaker_msgs/InitRequest.h>
#include <carmaker_msgs/InitResponse.h>


namespace carmaker_msgs
{

struct Init
{

typedef InitRequest Request;
typedef InitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Init
} // namespace carmaker_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carmaker_msgs::Init > {
  static const char* value()
  {
    return "c39177108282824e55cd272f345a59bb";
  }

  static const char* value(const ::carmaker_msgs::Init&) { return value(); }
};

template<>
struct DataType< ::carmaker_msgs::Init > {
  static const char* value()
  {
    return "carmaker_msgs/Init";
  }

  static const char* value(const ::carmaker_msgs::Init&) { return value(); }
};


// service_traits::MD5Sum< ::carmaker_msgs::InitRequest> should match
// service_traits::MD5Sum< ::carmaker_msgs::Init >
template<>
struct MD5Sum< ::carmaker_msgs::InitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carmaker_msgs::Init >::value();
  }
  static const char* value(const ::carmaker_msgs::InitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carmaker_msgs::InitRequest> should match
// service_traits::DataType< ::carmaker_msgs::Init >
template<>
struct DataType< ::carmaker_msgs::InitRequest>
{
  static const char* value()
  {
    return DataType< ::carmaker_msgs::Init >::value();
  }
  static const char* value(const ::carmaker_msgs::InitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carmaker_msgs::InitResponse> should match
// service_traits::MD5Sum< ::carmaker_msgs::Init >
template<>
struct MD5Sum< ::carmaker_msgs::InitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carmaker_msgs::Init >::value();
  }
  static const char* value(const ::carmaker_msgs::InitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carmaker_msgs::InitResponse> should match
// service_traits::DataType< ::carmaker_msgs::Init >
template<>
struct DataType< ::carmaker_msgs::InitResponse>
{
  static const char* value()
  {
    return DataType< ::carmaker_msgs::Init >::value();
  }
  static const char* value(const ::carmaker_msgs::InitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARMAKER_MSGS_MESSAGE_INIT_H
