// Generated by gencpp from file carmaker_msgs/Objects.msg
// DO NOT EDIT!


#ifndef CARMAKER_MSGS_MESSAGE_OBJECTS_H
#define CARMAKER_MSGS_MESSAGE_OBJECTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <carmaker_msgs/Object.h>

namespace carmaker_msgs
{
template <class ContainerAllocator>
struct Objects_
{
  typedef Objects_<ContainerAllocator> Type;

  Objects_()
    : header()
    , number_of_objects(0)
    , object()  {
    }
  Objects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , number_of_objects(0)
    , object(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _number_of_objects_type;
  _number_of_objects_type number_of_objects;

   typedef std::vector< ::carmaker_msgs::Object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::carmaker_msgs::Object_<ContainerAllocator> >> _object_type;
  _object_type object;





  typedef boost::shared_ptr< ::carmaker_msgs::Objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carmaker_msgs::Objects_<ContainerAllocator> const> ConstPtr;

}; // struct Objects_

typedef ::carmaker_msgs::Objects_<std::allocator<void> > Objects;

typedef boost::shared_ptr< ::carmaker_msgs::Objects > ObjectsPtr;
typedef boost::shared_ptr< ::carmaker_msgs::Objects const> ObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carmaker_msgs::Objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carmaker_msgs::Objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carmaker_msgs::Objects_<ContainerAllocator1> & lhs, const ::carmaker_msgs::Objects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.number_of_objects == rhs.number_of_objects &&
    lhs.object == rhs.object;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carmaker_msgs::Objects_<ContainerAllocator1> & lhs, const ::carmaker_msgs::Objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carmaker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::Objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::Objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::Objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::Objects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carmaker_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa0a3829c7ec278c7f0d3560362836b3";
  }

  static const char* value(const ::carmaker_msgs::Objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa0a3829c7ec278cULL;
  static const uint64_t static_value2 = 0x7f0d3560362836b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::carmaker_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carmaker_msgs/Objects";
  }

  static const char* value(const ::carmaker_msgs::Objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carmaker_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# std_msgs/Header\n"
"std_msgs/Header header\n"
"\n"
"# object information\n"
"uint16 number_of_objects\n"
"carmaker_msgs/Object[] object\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: carmaker_msgs/Object\n"
"# Object information\n"
"uint8 id\n"
"uint8 classification\n"
"uint8 lane_id\n"
"\n"
"float32 length \n"
"float32 width \n"
"float32 height \n"
"\n"
"carmaker_msgs/ObjectState state\n"
"\n"
"================================================================================\n"
"MSG: carmaker_msgs/ObjectState\n"
"float64 latitude                  # GCS Coordinates latitude\n"
"float64 longitude                 # GCS Coordinates longitude\n"
"float64 elevation                 # GCS Coordinates elevation\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"float32 roll                      # yaw in vehicle coordinates [rad]\n"
"float32 pitch                     # yaw in vehicle coordinates [rad]\n"
"float32 yaw                       # yaw in vehicle coordinates [rad]\n"
"float32 ego_roll                      # yaw in vehicle coordinates [rad]\n"
"float32 ego_pitch                     # yaw in vehicle coordinates [rad]\n"
"float32 ego_yaw                       # yaw in vehicle coordinates [rad]\n"
"\n"
"float32 roll_rate                      # yaw in vehicle coordinates [rad]\n"
"float32 pitch_rate                     # yaw in vehicle coordinates [rad]\n"
"float32 yaw_rate                       # yaw in vehicle coordinates [rad]\n"
"\n"
"float32 v_x                       # velocity in vehicle coordinates [m/s]\n"
"float32 v_y                       # velocity in vehicle coordinates [m/s]\n"
"float32 a_x                       # acceleration in vehicle coordinates [m/s^2]\n"
"float32 a_y                       # acceleration in vehicle coordinates [m/s^2]\n"
;
  }

  static const char* value(const ::carmaker_msgs::Objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carmaker_msgs::Objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.number_of_objects);
      stream.next(m.object);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carmaker_msgs::Objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carmaker_msgs::Objects_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "number_of_objects: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.number_of_objects);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object: ";
    if (v.object.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.object.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::carmaker_msgs::Object_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.object[i]);
    }
    if (v.object.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARMAKER_MSGS_MESSAGE_OBJECTS_H
