// Generated by gencpp from file carmaker_msgs/ObjectState.msg
// DO NOT EDIT!


#ifndef CARMAKER_MSGS_MESSAGE_OBJECTSTATE_H
#define CARMAKER_MSGS_MESSAGE_OBJECTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carmaker_msgs
{
template <class ContainerAllocator>
struct ObjectState_
{
  typedef ObjectState_<ContainerAllocator> Type;

  ObjectState_()
    : latitude(0.0)
    , longitude(0.0)
    , elevation(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , ego_roll(0.0)
    , ego_pitch(0.0)
    , ego_yaw(0.0)
    , roll_rate(0.0)
    , pitch_rate(0.0)
    , yaw_rate(0.0)
    , v_x(0.0)
    , v_y(0.0)
    , a_x(0.0)
    , a_y(0.0)  {
    }
  ObjectState_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , elevation(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , ego_roll(0.0)
    , ego_pitch(0.0)
    , ego_yaw(0.0)
    , roll_rate(0.0)
    , pitch_rate(0.0)
    , yaw_rate(0.0)
    , v_x(0.0)
    , v_y(0.0)
    , a_x(0.0)
    , a_y(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _elevation_type;
  _elevation_type elevation;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _ego_roll_type;
  _ego_roll_type ego_roll;

   typedef float _ego_pitch_type;
  _ego_pitch_type ego_pitch;

   typedef float _ego_yaw_type;
  _ego_yaw_type ego_yaw;

   typedef float _roll_rate_type;
  _roll_rate_type roll_rate;

   typedef float _pitch_rate_type;
  _pitch_rate_type pitch_rate;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef float _v_x_type;
  _v_x_type v_x;

   typedef float _v_y_type;
  _v_y_type v_y;

   typedef float _a_x_type;
  _a_x_type a_x;

   typedef float _a_y_type;
  _a_y_type a_y;





  typedef boost::shared_ptr< ::carmaker_msgs::ObjectState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carmaker_msgs::ObjectState_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectState_

typedef ::carmaker_msgs::ObjectState_<std::allocator<void> > ObjectState;

typedef boost::shared_ptr< ::carmaker_msgs::ObjectState > ObjectStatePtr;
typedef boost::shared_ptr< ::carmaker_msgs::ObjectState const> ObjectStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carmaker_msgs::ObjectState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carmaker_msgs::ObjectState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carmaker_msgs::ObjectState_<ContainerAllocator1> & lhs, const ::carmaker_msgs::ObjectState_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.elevation == rhs.elevation &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.ego_roll == rhs.ego_roll &&
    lhs.ego_pitch == rhs.ego_pitch &&
    lhs.ego_yaw == rhs.ego_yaw &&
    lhs.roll_rate == rhs.roll_rate &&
    lhs.pitch_rate == rhs.pitch_rate &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.v_x == rhs.v_x &&
    lhs.v_y == rhs.v_y &&
    lhs.a_x == rhs.a_x &&
    lhs.a_y == rhs.a_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carmaker_msgs::ObjectState_<ContainerAllocator1> & lhs, const ::carmaker_msgs::ObjectState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carmaker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::ObjectState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::ObjectState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::ObjectState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::ObjectState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::ObjectState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::ObjectState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carmaker_msgs::ObjectState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a12156275044859859afbe394466b70";
  }

  static const char* value(const ::carmaker_msgs::ObjectState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a12156275044859ULL;
  static const uint64_t static_value2 = 0x859afbe394466b70ULL;
};

template<class ContainerAllocator>
struct DataType< ::carmaker_msgs::ObjectState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carmaker_msgs/ObjectState";
  }

  static const char* value(const ::carmaker_msgs::ObjectState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carmaker_msgs::ObjectState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude                  # GCS Coordinates latitude\n"
"float64 longitude                 # GCS Coordinates longitude\n"
"float64 elevation                 # GCS Coordinates elevation\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"float32 roll                      # yaw in vehicle coordinates [rad]\n"
"float32 pitch                     # yaw in vehicle coordinates [rad]\n"
"float32 yaw                       # yaw in vehicle coordinates [rad]\n"
"float32 ego_roll                      # yaw in vehicle coordinates [rad]\n"
"float32 ego_pitch                     # yaw in vehicle coordinates [rad]\n"
"float32 ego_yaw                       # yaw in vehicle coordinates [rad]\n"
"\n"
"float32 roll_rate                      # yaw in vehicle coordinates [rad]\n"
"float32 pitch_rate                     # yaw in vehicle coordinates [rad]\n"
"float32 yaw_rate                       # yaw in vehicle coordinates [rad]\n"
"\n"
"float32 v_x                       # velocity in vehicle coordinates [m/s]\n"
"float32 v_y                       # velocity in vehicle coordinates [m/s]\n"
"float32 a_x                       # acceleration in vehicle coordinates [m/s^2]\n"
"float32 a_y                       # acceleration in vehicle coordinates [m/s^2]\n"
;
  }

  static const char* value(const ::carmaker_msgs::ObjectState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carmaker_msgs::ObjectState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.elevation);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.ego_roll);
      stream.next(m.ego_pitch);
      stream.next(m.ego_yaw);
      stream.next(m.roll_rate);
      stream.next(m.pitch_rate);
      stream.next(m.yaw_rate);
      stream.next(m.v_x);
      stream.next(m.v_y);
      stream.next(m.a_x);
      stream.next(m.a_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carmaker_msgs::ObjectState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carmaker_msgs::ObjectState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "elevation: ";
    Printer<double>::stream(s, indent + "  ", v.elevation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ego_roll: ";
    Printer<float>::stream(s, indent + "  ", v.ego_roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ego_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.ego_pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ego_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.ego_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll_rate: ";
    Printer<float>::stream(s, indent + "  ", v.roll_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch_rate: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v_x: ";
    Printer<float>::stream(s, indent + "  ", v.v_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v_y: ";
    Printer<float>::stream(s, indent + "  ", v.v_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "a_x: ";
    Printer<float>::stream(s, indent + "  ", v.a_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "a_y: ";
    Printer<float>::stream(s, indent + "  ", v.a_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARMAKER_MSGS_MESSAGE_OBJECTSTATE_H
