// Generated by gencpp from file carmaker_msgs/Object.msg
// DO NOT EDIT!


#ifndef CARMAKER_MSGS_MESSAGE_OBJECT_H
#define CARMAKER_MSGS_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <carmaker_msgs/ObjectState.h>

namespace carmaker_msgs
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : id(0)
    , classification(0)
    , lane_id(0)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , state()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : id(0)
    , classification(0)
    , lane_id(0)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _classification_type;
  _classification_type classification;

   typedef uint8_t _lane_id_type;
  _lane_id_type lane_id;

   typedef float _length_type;
  _length_type length;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef  ::carmaker_msgs::ObjectState_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::carmaker_msgs::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carmaker_msgs::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::carmaker_msgs::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::carmaker_msgs::Object > ObjectPtr;
typedef boost::shared_ptr< ::carmaker_msgs::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carmaker_msgs::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carmaker_msgs::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carmaker_msgs::Object_<ContainerAllocator1> & lhs, const ::carmaker_msgs::Object_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.classification == rhs.classification &&
    lhs.lane_id == rhs.lane_id &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carmaker_msgs::Object_<ContainerAllocator1> & lhs, const ::carmaker_msgs::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carmaker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carmaker_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "111800c1669628270d9a907e3619e0e5";
  }

  static const char* value(const ::carmaker_msgs::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x111800c166962827ULL;
  static const uint64_t static_value2 = 0x0d9a907e3619e0e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::carmaker_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carmaker_msgs/Object";
  }

  static const char* value(const ::carmaker_msgs::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carmaker_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Object information\n"
"uint8 id\n"
"uint8 classification\n"
"uint8 lane_id\n"
"\n"
"float32 length \n"
"float32 width \n"
"float32 height \n"
"\n"
"carmaker_msgs/ObjectState state\n"
"\n"
"================================================================================\n"
"MSG: carmaker_msgs/ObjectState\n"
"float64 latitude                  # GCS Coordinates latitude\n"
"float64 longitude                 # GCS Coordinates longitude\n"
"float64 elevation                 # GCS Coordinates elevation\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"float32 roll                      # yaw in vehicle coordinates [rad]\n"
"float32 pitch                     # yaw in vehicle coordinates [rad]\n"
"float32 yaw                       # yaw in vehicle coordinates [rad]\n"
"float32 ego_roll                      # yaw in vehicle coordinates [rad]\n"
"float32 ego_pitch                     # yaw in vehicle coordinates [rad]\n"
"float32 ego_yaw                       # yaw in vehicle coordinates [rad]\n"
"\n"
"float32 roll_rate                      # yaw in vehicle coordinates [rad]\n"
"float32 pitch_rate                     # yaw in vehicle coordinates [rad]\n"
"float32 yaw_rate                       # yaw in vehicle coordinates [rad]\n"
"\n"
"float32 v_x                       # velocity in vehicle coordinates [m/s]\n"
"float32 v_y                       # velocity in vehicle coordinates [m/s]\n"
"float32 a_x                       # acceleration in vehicle coordinates [m/s^2]\n"
"float32 a_y                       # acceleration in vehicle coordinates [m/s^2]\n"
;
  }

  static const char* value(const ::carmaker_msgs::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carmaker_msgs::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.classification);
      stream.next(m.lane_id);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carmaker_msgs::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carmaker_msgs::Object_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "classification: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.classification);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lane_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lane_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer< ::carmaker_msgs::ObjectState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARMAKER_MSGS_MESSAGE_OBJECT_H
