// Generated by gencpp from file carmaker_msgs/TrafficLight.msg
// DO NOT EDIT!


#ifndef CARMAKER_MSGS_MESSAGE_TRAFFICLIGHT_H
#define CARMAKER_MSGS_MESSAGE_TRAFFICLIGHT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace carmaker_msgs
{
template <class ContainerAllocator>
struct TrafficLight_
{
  typedef TrafficLight_<ContainerAllocator> Type;

  TrafficLight_()
    : header()
    , TrafficLightID(0)
    , TrafficLightState(0)  {
    }
  TrafficLight_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , TrafficLightID(0)
    , TrafficLightState(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _TrafficLightID_type;
  _TrafficLightID_type TrafficLightID;

   typedef uint8_t _TrafficLightState_type;
  _TrafficLightState_type TrafficLightState;





  typedef boost::shared_ptr< ::carmaker_msgs::TrafficLight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carmaker_msgs::TrafficLight_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLight_

typedef ::carmaker_msgs::TrafficLight_<std::allocator<void> > TrafficLight;

typedef boost::shared_ptr< ::carmaker_msgs::TrafficLight > TrafficLightPtr;
typedef boost::shared_ptr< ::carmaker_msgs::TrafficLight const> TrafficLightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carmaker_msgs::TrafficLight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carmaker_msgs::TrafficLight_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carmaker_msgs::TrafficLight_<ContainerAllocator1> & lhs, const ::carmaker_msgs::TrafficLight_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.TrafficLightID == rhs.TrafficLightID &&
    lhs.TrafficLightState == rhs.TrafficLightState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carmaker_msgs::TrafficLight_<ContainerAllocator1> & lhs, const ::carmaker_msgs::TrafficLight_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carmaker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::TrafficLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carmaker_msgs::TrafficLight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::TrafficLight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carmaker_msgs::TrafficLight_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::TrafficLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carmaker_msgs::TrafficLight_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carmaker_msgs::TrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df7500dfb83cf8c9771f4d242f622dc5";
  }

  static const char* value(const ::carmaker_msgs::TrafficLight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf7500dfb83cf8c9ULL;
  static const uint64_t static_value2 = 0x771f4d242f622dc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::carmaker_msgs::TrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carmaker_msgs/TrafficLight";
  }

  static const char* value(const ::carmaker_msgs::TrafficLight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carmaker_msgs::TrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# std_msgs/Header\n"
"std_msgs/Header header\n"
"\n"
"uint16 TrafficLightID\n"
"uint8 TrafficLightState\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::carmaker_msgs::TrafficLight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carmaker_msgs::TrafficLight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.TrafficLightID);
      stream.next(m.TrafficLightState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carmaker_msgs::TrafficLight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carmaker_msgs::TrafficLight_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "TrafficLightID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.TrafficLightID);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "TrafficLightState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.TrafficLightState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARMAKER_MSGS_MESSAGE_TRAFFICLIGHT_H
